[sel SEL_EXPLORATION top]
[uf 0 5 65278][uf 2 1]Auf E[uf 2 4 0] weitermachen[e]
[uf 0 5 65278][uf 2 1]Den Teleporter nutzen[e]
[uf 0 5 65278][uf 2 1]Nicht nutzen[e]

[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Ja.[e]
[uf 0 5 65278][uf 2 1]Warte.[e]

[sel SEL_CheckFull top]
[uf 0 5 65278][uf 2 1]Den Teleporter nutzen[e]
[uf 0 5 65278][uf 2 1]Nicht nutzen[e]

[msg MSG_ACCESS_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4001 0 0]Du hast den Tartarus bis zu Ebene [uf 2 4 0] erkundet. Wo willst du weitermachen?[n][uf 1 1][e]

[msg MSG_ACCESS_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5003 0 0]Gut, du hast Ebene [uf 2 4 0] erreicht. Wohin willst du jetzt springen?[n][uf 1 1][e]

[msg MSG_THEURGIA_FUKA_OK_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5145 0 0]Bist du bereit?[n][uf 1 1][e]

[msg MSG_THEURGIA_FUKA_OK_02 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ich versuche, dich auf eine stabilere Ebene zu führen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0]Ich kann zwar nicht mitkommen, aber ich gebe mein Bestes, um dich von hier oben zu unterstützen![n][uf 1 1][e]

[msg MSG_START_MITSURU_OK_10 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Verstanden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Solange du meinen Anweisungen folgst, kann ich dich über eine sichere Route lotsen.[n][uf 1 1][e]

[msg MSG_START_MITSURU_OK_11 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ebene [uf 2 4 0], sagst du? Verstanden. Der Teleporter müsste dich direkt hinbringen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Sei vorsichtig da draußen.[n][uf 1 1][e]

[msg MSG_START_FUKA_OK_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Okay, ich versteh schon.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ich finde eine sichere Route, folge also einfach meinen Anweisungen.[n][uf 1 1][e]

[msg MSG_START_FUKA_OK_11 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Du willst auf Ebene [uf 2 4 0]? Okay, wenn du den Teleporter nimmst, bist du blitzschnell da![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ich wünsche eine sichere Reise![n][uf 1 1][e]

[msg MSG_ADVICE_MITSURU_MAY [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4073 0 0]Ich muss dir etwas sagen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Weißt du noch, was ich gesagt habe? Dass der Tartarus in verschiedene Bereiche unterteilt ist?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Tja, durch Penthesileas Kraft habe ich ein ungewöhnliches Signal jenseits der 20. Ebene entdeckt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Es könnte sich etwas verschoben haben, also möchte ich, dass du sofort hingehst und dir das ansiehst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Wir zählen auf dich.[n][uf 1 1][e]

[msg MSG_ADVICE_FUKA_MAY [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5061 0 0]Anführerin, hast du kurz Zeit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Weißt du noch? Kirijo-senpai hat gesagt, dass der Tartarus in mehrere Bereiche unterteilt ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Tja, einer dieser Bereiche sollte auf der 22. Ebene enden, aber ich empfange von dort ein merkwürdiges Signal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Es wirkt instabil, als würde es sich bald bewegen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Ich würde für die Expedition heute also empfehlen, die 22. Ebene zu erkunden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0]Sei vorsichtig ... und viel Glück.[n][uf 1 1][e]

[msg MND_WARP_FIRST]
[uf 0 5 65278][uf 2 1]Die Konsole zeigt eine Ziffernfolge an ...[n][uf 1 1][e]

[msg MSG_WARP_FIRST_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4061 0 0]Hmm ... verstehe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Wähle auf dem Gerät bitte die 1. Ebene aus. Das sollte dich zurückschicken.[n][uf 1 1][e]

[msg MSG_WARP_FIRST_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5079 0 0]Oh, wie interessant![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Kannst du da die 1. Ebene wählen? Damit müsstest du wieder hierher zurückkehren.[n][uf 1 1][e]

[msg MND_WARP_NOT_BOOT]
[uf 0 5 65278][uf 2 1]Was ist das? So etwas habe ich noch nie gesehen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Wie dem auch sei, es scheint nicht zu funktionieren.[n][uf 1 1][e]

[msg MND_WARP_NOT_BOOT_2]
[uf 0 5 65278][uf 2 1]Wenn ich im Tartarus einen Einbahnstraßen-Teleporter verwende, lande ich wohl wieder hier.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich komme damit aber offenbar nicht zurück zu der Ebene, auf der ich zuletzt war.[n][uf 1 1][e]

[msg MSG_MITSURU_GREET [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10099 0 0]Dank Yamagishi kann ich auch mit dir auf Erkundung gehen. Aber ich würde gerne bei der Vier-Personen-Strategie bleiben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10100 0 0]Nur, damit wir Verstärkung haben und uns im Notfall jemand zur Hilfe kommen kann.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 1 0 1 10101 0 0]Und vergiss nicht, was beim letzten Vollmond passiert ist. Wir dürfen Yamagishi nicht alleine lassen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 1 0 1 10102 0 0]Ich überlasse dir die Zusammenstellung der Gruppe. Ich weiß, du kriegst das hin.[n][uf 1 1][e]

[msg MSG_FUKA_GREET [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 2 65535 65535 0 0][uf 3 1 1 0 1 10103 0 0]Ich helfe, wo ich kann. Geben wir unser Bestes![n][uf 1 1][e]

[msg DESC_FLOOR21_NG_MITU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 3 0 65535 4032 0 0]Augenblick ... Gut, der Weg ist sicher.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Und ich bin neugierig, was auf der nächsten Ebene wartet. Bitte geh weiter.[n][uf 1 1][e]

[msg DESC_FLOOR21_NG_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Bitte warte noch kurz ... Okay, es ist sicher.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Ich bin neugierig auf die nächste Ebene. Könnt ihr noch weitermachen?[n][uf 1 1][e]

[msg MSG_Mitsuru_NotFull [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4008 0 0]Sind alle bereit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 65535 0 0]Ich rate dazu, wenn möglich immer mit voller Gruppe loszuziehen.[n][uf 1 1][e]

[msg MSG_Fuka_NotFull [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 65535 0 0][uf 3 1 3 0 65535 5008 0 0]Bereit für die Erkundung?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 65535 0 0]Oh, äh ... bist du sicher, dass du nicht mit einer vollen Gruppe losziehen willst?[n][uf 1 1][e]

