[sel SEL_YESNO top]
[uf 0 5 65278][uf 2 1]Öffnen[e]
[uf 0 5 65278][uf 2 1]Nicht öffnen[e]

[msg MND_TBOX_MEDAL]
[uf 0 5 65278][uf 2 1]Ich habe [uf 4 4 1 0 1 0] [uf 0 1 2][uf 2 4 2][uf 0 1 27]-mal. Mit [uf 0 1 2][uf 2 4 1][uf 0 1 27] sollte ich es öffnen können.[n][uf 1 1][e]

[msg MND_TBOX_MEDAL_OPEN]
[uf 0 5 65278][uf 2 1]Ich habe [uf 0 1 2][uf 2 4 1][uf 0 1 27] meiner [uf 4 4 1 0 1 0] verbraucht, es sind noch [uf 2 4 3] übrig.[n][uf 1 1][e]

[msg MND_TBOX_MEDAL_NOT_ENOUG]
[uf 0 5 65278][uf 2 1]Hätte ich [uf 0 1 2][uf 2 4 1][uf 0 1 27] [uf 4 4 1 0 1 0], könnte ich es öffnen, aber ich habe gerade nur [uf 0 1 2][uf 2 4 2][uf 0 1 27].[n][uf 1 1][e]

[msg MND_TBOX_MedalNone]
[uf 0 5 65278][uf 2 1]Ich habe das nicht dabei: [uf 4 4 1 0 1 0].[n]Ich benötige [uf 0 1 2][uf 2 4 1][uf 0 1 27], um es zu öffnen.[n][uf 1 1][e]

[msg MSG_TBOX_RETURN_FUKA [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Ich erfasse hier keine Schatztruhen mehr.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Es ist immer noch gefährlich, kommt also möglichst bald zurück.[n][uf 1 1][e]

[msg MSG_TBOX_OPEN_TUTO [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0][uf 3 1 1 0 1 20523 0 0]Das könnte nützlich sein. Du darfst entscheiden, was wir damit machen.[n][uf 1 1][e]

[msg MSG_1ST_TRY_MEDAL_OPENED [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0][uf 3 1 3 0 65535 4607 0 0]Ah, das dachte ich mir ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 50 0 0]Ein [uf 0 1 39]Zwielichtfragment[uf 0 1 27]. Damit könnt ihr die Vorrichtungen im Tartarus betätigen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Überall, wo es Schatten gibt, werdet ihr darauf stoßen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Falls ihr eins entdeckt, solltet ihr es mitnehmen.[n][uf 1 1][e]

[msg MND_GET_ARCANA_CARD]
[uf 0 5 65278][uf 2 1]"[uf 4 4 1 0 1 0]" zeigt eine Reaktion ...[n][uf 1 1][e]

[msg PFM_GET_CARD_TEMPERANCE]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Mäßigkeit" kann[n]jetzt während Shuffle Time erscheinen.[n][uf 1 1][e]

[msg PFM_GET_CARD_DEVIL]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Teufel" kann[n]jetzt während Shuffle Time erscheinen.[n][uf 1 1][e]

[msg PFM_GET_CARD_TOWER]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Turm" kann[n]jetzt während Shuffle Time erscheinen.[n][uf 1 1][e]

[msg PFM_GET_CARD_STAR]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Stern" kann[n]jetzt während Shuffle Time erscheinen.[n][uf 1 1][e]

[msg PFM_GET_CARD_MOON]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Mond" kann[n]jetzt während Shuffle Time erscheinen.[n][uf 1 1][e]

[msg PFM_GET_CARD_SUN]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Sonne" kann[n]jetzt während Shuffle Time erscheinen.[n][uf 1 1][e]

[msg PFM_GET_CARD_JUDGEMENT]
[uf 0 5 65278][uf 2 1]Die "Großes Arkana"-Karte "Gericht" kann[n]jetzt während Shuffle Time erscheinen.[n][uf 1 1][e]

[msg MSG_ESCAPE_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5025 0 0]Sieht nach Sackgasse aus. Willst du sofort umkehren?[n][uf 1 1][e]

[sel SEL_ESCAPE_HERO top]
[uf 0 5 65278][uf 2 1]Monad verlassen[e]
[uf 0 5 65278][uf 2 1]Mit Erkundung fortfahren[e]

[msg MSG_ESCAPE_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Okay.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Sei vorsichtig auf dem Weg zurück.[n][uf 1 1][e]

[msg MSG_ESCAPE_FUKA_11 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Oh, hast du vielleicht etwas übersehen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Es gibt zwar keine Gegner mehr, ist aber trotzdem noch gefährlich.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Sei bitte vorsichtig, wenn du weiter erkundest.[n][uf 1 1][e]

[msg MND_ARAGAKI_REMIND]
[uf 0 5 65278][uf 2 1]Das hätte gut zu Aragaki gepasst, aber er ist nicht mehr unter uns ...[n][uf 1 1][e]

[msg MSG_TUTO01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5071 0 0]So etwas hat Shuji dir mal gegeben, oder, [uf 4 1]-chan?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Das scheint echt selten zu sein. Erstaunlich, dass es hier war.[n][uf 1 1][e]

[msg MND_TUTO02]
[uf 0 5 65278][uf 2 1]Der Besitzer des Antiquitätenladens könnte daraus Ausrüstung herstellen.[n][uf 1 1][e]

[msg MSG_TUTO03 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Hier habt ihr alles gesehen. Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Das ist ein guter Zeitpunkt, um zu verschwinden. Bitte verlasst den Ort durch die Tür.[n][uf 1 1][e]

[sel SEL_EQUIP_UPDATE_00 top]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 0 0] ausrüsten[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_01 top]
[uf 0 5 65278][uf 2 1]Mit neuer Ausrüstung ersetzen[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_02 top]
[uf 0 5 65278][uf 2 1]Yukari geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_03 top]
[uf 0 5 65278][uf 2 1]Junpei geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_04 top]
[uf 0 5 65278][uf 2 1]Sanada geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_05 top]
[uf 0 5 65278][uf 2 1]Mitsuru geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_06 top]
[uf 0 5 65278][uf 2 1]未使用
[e]

[sel SEL_EQUIP_UPDATE_07 top]
[uf 0 5 65278][uf 2 1]Aigis geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_08 top]
[uf 0 5 65278][uf 2 1]Amada geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_09 top]
[uf 0 5 65278][uf 2 1]Koromaru geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[sel SEL_EQUIP_UPDATE_10 top]
[uf 0 5 65278][uf 2 1]Aragaki geben[e]
[uf 0 5 65278][uf 2 1]Aktuelle Ausrüstung behalten[e]

[msg MND_EQUIP_UPDATE_HERO_00]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] scheint stärker zu sein als meine aktuelle Waffe.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_YUKARI_ [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]Hey, schicker Bogen! Der ist für mich, oder?[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_JUNPEI_ [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Yo, diese Waffe sieht mal krass aus! Die solltest du nur einem wahren Meister geben, also ...[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_SANADA_ [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3094 0 0]Oh, eine neue Waffe? Die sieht noch besser als meine jetzige.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_MITSURU [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4086 0 0]Ah, eine gute Waffe. Darf ich die verwenden?[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_FUKA_00 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5087 0 0]Oh, eine Waffe. Die könnte Koro-chan bestimmt gut gebrauchen.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6080 0 0]Neue Ausrüstung erlangt. Scheint ein Upgrade zu sein.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AMADA_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7005 0 0]Eine neue Waffe? Darf ich sie einsetzen?![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_KORO_00 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Rawuff! Rawuff![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 1 65535 65535 0 0][uf 3 1 3 0 65535 9007 0 0]Was haben wir denn hier? Das solltest du mir geben.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6087 0 0]Oh, neue Ausrüstung! Darf ich sie einsetzen?[n][uf 1 1][e]

[msg MND_EQUIP_UPDATE_HERO_01]
[uf 0 5 65278][uf 2 1][uf 4 4 1 0 1 0] scheint stärker zu sein als meine aktuelle Waffe.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_YUKARI__2 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]Ooh, das sieht super aus! Darf ich das haben?[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__2 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2001 0 0]Hey, krasse Rüstung. Die würde meinen inneren Charme zum Vorschein bringen.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_SANADA__2 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3094 0 0]Diese Rüstung würde mir stehen. Darf ich sie haben?[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_MITSURU_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4086 0 0]Welche prächtige Rüstung. Die sollte noch besser sein als meine aktuelle.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_FUKA_01 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0][uf 3 1 3 0 65535 5087 0 0]Oh! Diese Rüstung wäre perfekt für Koro-chan geeignet.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_3 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6080 0 0]Das scheint für die Abwehr gedacht zu sein. Darf ich es ausrüsten?[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AMADA_0_2 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7005 0 0]Äh, die neue Rüstung passt mir zwar noch nicht, aber ich wachse auf jeden Fall hinein![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_KORO_01 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Rawuff! Rawuff![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_2 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9007 0 0]Hey, schicker Fund. Wenn es sonst keiner will, nehme ich es.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AEGIS_0_4 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6087 0 0]Diese Rüstung ist robuster als meine aktuelle. Darf ich sie anlegen?[n][uf 1 1][e]

[msg MND_EQUIP_UPDATE_MULTI]
[uf 0 5 65278][uf 2 1]Wem soll ich [uf 4 4 1 0 1 0] geben?[n][uf 1 1][e]

[sel SEL_PARTY top]
[uf 0 5 65278][uf 2 1]Selbst ausrüsten[e]
[uf 0 5 65278][uf 2 1]Yukari[e]
[uf 0 5 65278][uf 2 1]Junpei[e]
[uf 0 5 65278][uf 2 1]Sanada[e]
[uf 0 5 65278][uf 2 1]Mitsuru[e]
[uf 0 5 65278][uf 2 1]Fuuka[e]
[uf 0 5 65278][uf 2 1]Aigis[e]
[uf 0 5 65278][uf 2 1]Amada[e]
[uf 0 5 65278][uf 2 1]Koromaru[e]
[uf 0 5 65278][uf 2 1]Aragaki[e]
[uf 0 5 65278][uf 2 1]Jetzt nicht ausrüsten[e]

[msg MND_EQUIP_UPDATE_HERO_10]
[uf 0 5 65278][uf 2 1]Ich habe das ausgerüstet: [uf 4 4 1 0 1 0][n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_YUKARI__3 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1039 0 0]Danke. Ich passe gut darauf auf![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_JUNPEI__3 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 3 0 65535 2117 0 0]Yeah, Zeit für ein Upgrade, Baby! Immer weiter so![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_SANADA__3 [Akihiko Sanada]]
[uf 0 5 65278][uf 2 1][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3042 0 0]Gute Ausrüstung ist zwar kein Ersatz für Training, aber trotzdem hilfreich.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_MITSURU_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4038 0 0]Danke. Ich werde dich nicht enttäuschen.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_FUKA_10 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 50 0 0]未使用
[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6038 0 0]Ausrüstungs-Upgrade bestätigt. Verbesserte Kampfleistung erwartet.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AMADA_1 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7040 0 0]Vielen Dank. Ich werde mein Bestes geben![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_KORO_10 [Koromaru]]
[uf 0 5 65278][uf 2 1][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8012 0 0]Wuff, wuff![n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_ARAGAKI_3 [Shinjiro Aragaki]]
[uf 0 5 65278][uf 2 1][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9051 0 0]Gute Wahl. Du wirst es nicht bereuen.[n][uf 1 1][e]

[msg MSG_EQUIP_UPDATE_AEGIS_1_2 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Ausrüstungs-Upgrade bestätigt. Damit werde ich noch besser![n][uf 1 1][e]

[msg MSG_HIGH_RARE_TUTO_MITU_ [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Ich erfasse den Schatten nicht mehr. Er muss zu weit weg sein.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_TUTO_MITU__2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 3 65535 50 0 0]Tja, er hat die Truhe. Aber zumindest weiß er, dass wir hier sind.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Wenn wir weiter Schatztruhen öffnen, wird er uns bemerken.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Suchen wir also weiter nach ihnen, dann läuft er uns wieder über den Weg.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_TUTO_FUKA_ [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Ich spüre den Schatten nicht mehr. Mittlerweile ist er wohl zu weit entfernt.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_TUTO_FUKA__2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 65535 50 0 0]Er hat die Schatztruhe, aber er hat uns bemerkt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Wenn wir weiter Truhen öffnen, sollte er uns bemerken.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Suchen wir weiter nach ihnen.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_BTL_MITU_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Der Schatten kommt in unsere Richtung. Bereit machen![n][uf 1 1][e]

[msg MSG_HIGH_RARE_BTL_MITU_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Der Zielschatten wurde eliminiert. Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 50 0 0]Auf dieser Ebene gibt es keine Schatten mehr. Gehen wir weiter.[n][uf 1 1][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Der Schatten kommt direkt auf uns zu! Das ist unsere Chance! Bereit?[n][uf 1 1][e]

[msg MSG_HIGH_RARE_BTL_FUKA_0_2 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Ihr habt den Schatten besiegt. Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 65535 50 0 0]Ich erfasse keine Gegner mehr auf dieser Ebene. Gehen wir weiter.[n][uf 1 1][e]

