[msg MSG_000_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Na, wenn haben wir denn da. Wie findest du in Kyoto so das Essen, [uf 4 1]-chan?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Ehrlich gesagt, sagt mir die pflanzliche Kost hier nicht sonderlich zu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Ich habe das Essen im Souvenirladen versucht, es war aber nicht so gut wie erhofft.[n][uf 1 1][e]

[msg MSG_001_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Du bist immer noch grün hinter den Ohren.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Hör mir gut zu. Kein echter Gourmet würde sich in einem Yukata erwischen lassen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Wir essen![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Unser Bauch wird dicker![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Die Schärpe wird zu eng![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Also lockern wir ihn![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Dann essen wir mehr![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Die Schärpe wird noch enger![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Dann fällt sie ab![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Wir stehen nackt da![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]Verstehst du?[n][uf 1 1][e]

[msg MSG_002_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]In völliger Nacktheit und mit kaltem Bauch. Das nenne ich einen echten Notfall.[n][uf 1 1][e]

[msg MSG_003_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12609 0 0]Oh, du bist es![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Ich überlege gerade, was es als Nächstes gibt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Bisher hatte ich Senbei, Nama-Yatsuhashi, mehr Nama-Yatsuhashi, Senmaizuke ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Dann noch mehr Nama-Yatsuhashi, dann wieder Senbai und noch mehr Senbai. Und jetzt?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Nama-Yatsuhashi.[e]
[uf 0 5 65278][uf 2 1]Senmaizuke.[e]
[uf 0 5 65278][uf 2 1]Iss, was immer du willst.[e]

[msg MSG_005_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Ah richtig, die ungebacken rohen Süßigkeiten! Dessert ergibt in der Tat am meisten Sinn.[n][uf 1 1][e]

[msg MSG_006_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Ja! Eintausend Scheiben. Hm, ganz schön viel, oder? Trotzdem werde ich es versuchen![n][uf 1 1][e]

[msg MSG_007_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Was?! Ich soll entscheiden?! Wie soll ich das bei dem Hunger schaffen ...[n][uf 1 1][e]

[msg MSG_008_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Zu viel des Guten kann schlecht sein. Und das gilt auch für Kyotos gesunde Küche. Wie tiefgreifend.[n][uf 1 1][e]

[msg MSG_009_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Kyotos Küche mag gesund sein, doch isst man in Übermaßen, ist das egal ...[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

