[msg MSG_000_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0]Oh, [uf 4 1]-san ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ähm ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0]W-Was willst du denn?![n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Ich wollte nur mit dir reden.[e]
[uf 0 5 65278][uf 2 1]Nichts Bestimmtes.[e]

[msg MSG_002_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 3 0 65535 11491 0 0]I-I-Ich weiß nicht, was ich sagen soll![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Oh, äh ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Tut mir leid ...[n][uf 1 1][e]

[msg MSG_003_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 3 0 65535 11491 0 0]W-Warum redest du mit mir, wenn du nichts zu sagen hast?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Oh, äh ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Tut mir leid ...[n][uf 1 1][e]

[msg MSG_004_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]E-Es tut mir leid ...[n][uf 1 1][e]

[msg MSG_005_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11404 0 0][uf 4 1]-san ... Ähm ... Wegen neulich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ich, äh ... hab irgendwie überreagiert und, äh ... wollte mich nur entschuldigen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ich werde total nervös, wenn ich mit Leuten reden muss ... Dagegen sollte ich was tun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0]Besonders schlimm ist es bei Jungs ... Ich würde am liebsten wegrennen ...[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Die Hälfte der Schüler sind Jungs.[e]
[uf 0 5 65278][uf 2 1]Die halbe Weltbevölkerung besteht aus Jungs.[e]
[uf 0 5 65278][uf 2 1]Aber ich bin ein Mädchen.[e]

[msg MSG_007_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11472 0 0]S-Stimmt ... I-Ich hätte auf eine Mädchenschule gehen sollen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Aber dafür ist es jetzt zu spät. Ich bin schon fast drei Jahre hier.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ich muss mich mehr bemühen, diese Phobie zu überwinden.[n][uf 1 1][e]

[msg MSG_008_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11472 0 0]Oh Mann ... Jetzt habe ich sogar Angst, nach draußen zu gehen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Aber ... ich kann ja nicht mein ganzes Leben lang Angst haben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ich muss mich mehr bemühen, diese Phobie zu überwinden.[n][uf 1 1][e]

[msg MSG_009_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 3 0 65535 11487 0 0]I-Ich weiß! Aber warum bin ich dann so nervös ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]T-Tut mir leid, so bin ich dem Schülerrat keine große Hilfe ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ich muss mich mehr bemühen, diese Phobie zu überwinden.[n][uf 1 1][e]

[msg MSG_010_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11434 0 0]D-Danke. Ich versuche, mein Bestes zu geben ...[n][uf 1 1][e]

[msg MSG_011_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 1 0][uf 3 1 3 0 65535 11465 0 0]H-Hallo![n][uf 1 1][e]

[sel SEL_012_0_0 top]
[uf 0 5 65278][uf 2 1]Hallo.[e]
[uf 0 5 65278][uf 2 1]Oh, hallo.[e]

[msg MSG_013_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11493 0 0]Ich konnte dir Hallo sagen![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Aber ... Je mehr ich darüber nachdenke, desto nervöser werde ich ...[n][uf 1 1][e]

[msg MSG_014_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11493 0 0]Ich konnte dir Hallo sagen![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Aber ... Je mehr ich darüber nachdenke, desto nervöser werde ich ...[n][uf 1 1][e]

[msg MSG_015_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11450 0 0]Hoffentlich kriege ich das irgendwann besser hin ...[n][uf 1 1][e]

[sel SEL_016_0_0 top]
[uf 0 5 65278][uf 2 1]Lass uns zusammen abhängen.[e]
[uf 0 5 65278][uf 2 1]Viel Erfolg.[e]

[msg MSG_017_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 1 0][uf 3 1 3 0 65535 11475 0 0]Was ...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0]Ä-Ä-Ä-hm ... Das kommt so plötzlich, äh ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0]D-Darüber muss ich nachdenken![n][uf 1 1][e]

[msg MSG_018_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11422 0 0]D-Danke, ich werd's versuchen ...[n][uf 1 1][e]

[msg MSG_019_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11416 0 0]E-Entschuldigung ...[n][uf 1 1][e]

[msg MSG_020_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0]Ich gebe mein Bestes ...[n][uf 1 1][e]

[msg MSG_021_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0][uf 3 1 3 0 65535 11461 0 0]H-Hallo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ähm, als du mich neulich gefragt hast, ob ich was mit dir machen will ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Na ja, i-ich hab nachgedacht ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11463 0 0]Ähm, wenn du Lust hast, äh, würdest du vielleicht gerne, äh ...?[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]Gehen wir zusammen nach Hause.[e]
[uf 0 5 65278][uf 2 1]Sorry, heute bin ich beschäftigt.[e]

[msg MSG_023_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 3 0 65535 11423 0 0]O-O-O-Okay![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Dann, äh, mache ich mich mal fertig ...[n][uf 1 1][e]

[msg MSG_024_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11416 0 0]Oh, v-verstehe ... Tut mir leid ...[n][uf 1 1][e]

[msg MSG_025_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11461 0 0]H-Hallo![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]H-Hast du heute Zeit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11463 0 0]Willst du, äh ...?[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Gehen wir zusammen nach Hause.[e]
[uf 0 5 65278][uf 2 1]Sorry, heute bin ich beschäftigt.[e]

[msg MSG_027_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 3 0 65535 11423 0 0]O-O-O-Okay![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Dann, äh, mache ich mich mal fertig ...[n][uf 1 1][e]

[msg MSG_028_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11416 0 0]Oh, v-verstehe ... Tut mir leid ...[n][uf 1 1][e]

[msg MSG_029_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11405 0 0]Oh, [uf 4 1]-san ... Bist du auf dem Heimweg?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Äh, willst du Gesellschaft ...?[n][uf 1 1][e]

[msg MND_030_0_0]
[uf 0 5 65278][uf 2 1]Chihiro will mich anscheinend nach Hause bringen.[n][uf 1 1][e]

[msg MND_031_0_0]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit ihr verbringen?[n][uf 1 1][e]

[sel SEL_032_0_0 top]
[uf 0 5 65278][uf 2 1]Zeit mit ihr verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link-Status anzeigen[e]
[uf 0 5 65278][uf 2 1]Jetzt nicht[e]

[msg MSG_033_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11423 0 0]Oh! O-Okay![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Oh, aber wäre es in Ordnung, wenn wir vorher kurz bei der Bibliothek vorbeigucken?[n][uf 1 1][e]

[msg MSG_034_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 3 0 65535 11432 0 0]O-Oh, v-vielen Dank![n][uf 1 1][e]

[msg MSG_035_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Ä-Ähm, das ist mir echt unangenehm, aber ... hilfst du mir bei meinen Hausaufgaben?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Es geht um Mathe ... Reden wir in der Bibliothek darüber.[n][uf 1 1][e]

[msg MSG_036_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11434 0 0]Vielen Dank ...[n][uf 1 1][e]

[msg MSG_037_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Alleine ist es so einsam ...[n][uf 1 1][e]

[msg MSG_038_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11468 0 0]O-Oh! Freut mich zu hören ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 4 25 109]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 1 0]Ähm! W-Wenn das so ist ...[n][uf 1 1][e]

[msg MSG_039_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 1 0]M-Magst du mit zu mir kommen? Ist ein bisschen weit, aber ...[n][uf 1 1][e]

[msg MSG_040_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11481 0 0]D-Danke, [uf 4 1]-san ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]D-Dann, ähm ... ich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 1 0]Ich will mit dir zusammen sein ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 1 0]M-Magst du mit zu mir kommen? Meine Mutter kommt heute erst später nach Hause, glaube ich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 1 0]Na los ...[n][uf 1 1][e]

[msg MSG_041_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11432 0 0]Danke schön![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Heute findet kein Treffen statt, wir haben das Schülerratszimmer also ganz für uns.[n][uf 1 1][e]

[msg MSG_042_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]O-Oh, sorry. Ich ... wollte mich nicht aufdrängen ...[n][uf 1 1][e]

[msg MSG_043_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11452 0 0]Oh ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 4 25 109]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11410 0 0]B-Brauchst du etwas?[n][uf 1 1][e]

[msg MSG_044_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11452 0 0][uf 4 25 109]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ä-Ähm ... [uf 4 1]-san. Ich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11410 0 0]Ist nicht so wichtig. Was willst du?[n][uf 1 1][e]

[sel SEL_045_0_0 top]
[uf 0 5 65278][uf 2 1]Ich möchte mich entschuldigen.[e]
[uf 0 5 65278][uf 2 1]Bitte vergib mir.[e]
[uf 0 5 65278][uf 2 1]Es ist nichts.[e]

[msg MSG_046_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11483 0 0][uf 4 25 109]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ehrlich gesagt, hätte ich nicht gedacht, dass du noch mal zu mir kommst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Deine Fürsorge hat mich glücklich gemacht. Ich hätte früher damit rausrücken sollen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11404 0 0]Ähm ... Wollen wir vielleicht wann anders mal was zusammen unternehmen.[n][uf 1 1][e]

[msg MND_047_0_0]
[uf 0 5 65278][uf 2 1]Wir beide haben uns versöhnt![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich sollte bei nächster Gelegenheit mit ihr was unternehmen.[n][uf 1 1][e]

[msg MSG_048_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0][uf 4 25 109]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Wenn das stimmt, hättest du dich einfach nicht so blöd benehmen sollen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11472 0 0][uf 4 25 109]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11490 0 0]Mir ist inzwischen alles egal ...[n][uf 1 1][e]

[msg MND_049_0_0]
[uf 0 5 65278][uf 2 1]Chihiro ist immer noch abweisend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich sollte in ein paar Tagen wieder mit ihr reden, um unsere Beziehung zu kitten.[n][uf 1 1][e]

[msg MSG_050_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11416 0 0]Oh ... ähm ... Bis dann.[n][uf 1 1][e]

[msg MSG_051_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]Heute bin ich beschäftigt ...[n][uf 1 1][e]

[msg MSG_052_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11405 0 0]Oh, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Seit ich dich kenne, ist ein Tag schöner als der andere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Weil du mich so unterstützt, habe ich das Gefühl, dass ich alles schaffen kann ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11451 0 0]Hoffentlich kann ich dir so helfen, wie du mir geholfen hast.[n][uf 1 1][e]

[msg MND_053_0_0]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und Chihiro.[n][uf 1 1][e]

[msg MSG_054_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11405 0 0]Oh, [uf 4 1]-san ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Seit ich dich kenne, ist ein Tag schöner als der andere.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ich ... Ich weiß, dass ich vielen Leuten Ärger bereitet habe.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Und ich habe meine Probleme auf dich abgewälzt ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Aber dass wird nicht wieder passieren.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11451 0 0]Ich will so zuverlässig sein wie die Schülerratspräsidentin ... Wünschst du mir Glück?[n][uf 1 1][e]

[msg MND_055_0_0]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und Chihiro.[n][uf 1 1][e]

[msg MSG_056_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ähm, als du mich neulich gefragt hast, ob ich was mit dir machen will ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Na ja, i-ich hab nachgedacht ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ähm, wenn du Lust hast, äh, würdest du vielleicht gerne, äh ...?[n][uf 1 1][e]

[msg MSG_057_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]H-Hast du heute Zeit?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Willst du, äh ...?[n][uf 1 1][e]

[msg MSG_058_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Gehst du jetzt eigentlich nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Äh, willst du Gesellschaft ...?[n][uf 1 1][e]

[msg MSG_059_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11463 0 0][uf 4 1]-san ... Ähm, endlich sind die Prüfungen vorbei.[n][uf 1 1][e]

[msg MSG_060_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11409 0 0]Oh, [uf 4 1]-san. Endlich sind die Prüfungen vorbei.[n][uf 1 1][e]

[msg MSG_061_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ä-Ähm, uh ...[n][uf 1 1][e]

[msg MSG_062_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Ä-Ähm, hoffentlich hast du gut abgeschnitten. Jetzt kann es mit dem Schülerrat weitergehen.[n][uf 1 1][e]

[msg MSG_063_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Unused[n][uf 1 1][e]

[msg MSG_064_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 3 0 65535 11404 0 0]Oh, [uf 4 1]-san ... Bist du auf dem Heimweg?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Äh, willst du Gesellschaft ...?[n][uf 1 1][e]

[msg MSG_064_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Gehst du jetzt nach Hause? Äh, darf ich dich begleiten ...?[n][uf 1 1][e]

[msg MSG_065_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11423 0 0]Oh! O-Okay![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Eigentlich würde ich gerne vorher noch woanders hin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Kommst du mit zur Einkaufsstraße?[n][uf 1 1][e]

[msg MSG_066_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 3 0 65535 11405 0 0]Oh, [uf 4 1]-san ... Wie läuft es so bei dir?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Eigentlich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Falls du Zeit hast, würde ich dich gerne um einen Gefallen bitten.[n][uf 1 1][e]

[msg MSG_066_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Eigentlich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Falls du Zeit hast, würde ich dich gerne um einen Gefallen bitten.[n][uf 1 1][e]

[msg MSG_067_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11408 0 0]Oh, [uf 4 1]-san ... Hast du heute schon was vor?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Wollen wir vielleicht zusammen nach Hause gehen, falls du Zeit hast?[n][uf 1 1][e]

[msg MSG_067_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Oh, hast du heute schon was vor?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Wollen wir vielleicht zusammen nach Hause gehen, falls du Zeit hast?[n][uf 1 1][e]

[msg MSG_068_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11432 0 0]Oh, das ist schön![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]D-Dann ... Wie wäre es, wenn wir uns ins Café setzen?[n][uf 1 1][e]

[msg MSG_069_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11402 0 0]Oh, [uf 4 1]-san ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Ähm ... Hast du heute nach der Schule Zeit ...?[n][uf 1 1][e]

[msg MSG_069_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Ähm ... Hast du heute nach der Schule Zeit ...?[n][uf 1 1][e]

[msg MSG_070_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11484 0 0]Oh, gut![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ähm ... Heute würde ich mich gerne entspannt irgendwo mit dir unterhalten.[n][uf 1 1][e]

[msg MSG_071_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11409 0 0]Hallo, [uf 4 1]-san. Gehst du jetzt nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Falls du nichts dagegen hast ... würde ich dich gerne begleiten.[n][uf 1 1][e]

[msg MSG_071_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Gehst du jetzt nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Falls du nichts dagegen hast ... würde ich dich gerne begleiten.[n][uf 1 1][e]

[msg MSG_072_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11451 0 0]Danke schön![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Könnten wir zur Einkaufsstraße gehen? Ich wollte in den Buchladen ...[n][uf 1 1][e]

[msg MSG_073_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11402 0 0]Oh, [uf 4 1]-san ... Wolltest du gerade gehen??[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ähm ... Ich würde gerne wieder zum Buchladen gehen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Ich bin zwar ein hoffnungsloser Fall, aber ...[n][uf 1 1][e]

[msg MSG_073_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Wolltest du eigentlich gerade gehen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ähm ... Ich würde gerne wieder zum Buchladen gehen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Ich bin zwar ein hoffnungsloser Fall, aber ...[n][uf 1 1][e]

[msg MSG_074_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11467 0 0]Oh, vielen Dank![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ehrlich gesagt, hätte ich mich allein nicht getraut, aber mit dir zusammen traue ich mich alles ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 2 65535 65535 0 0]Ich sollte mutiger sein! Lass uns gehen, [uf 4 1]-san![n][uf 1 1][e]

[msg MSG_075_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11483 0 0]Oh ... Hallo, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Hast du nachher Zeit? Ich würde gerne zusammen mit dir lernen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0]Eigentlich ... wollte ich auch mit dir reden.[n][uf 1 1][e]

[msg MSG_075_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Hast du nachher Zeit? Ich würde gerne zusammen mit dir lernen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0][uf 3 1 3 0 65535 11454 0 0]Eigentlich ... wollte ich auch mit dir reden.[n][uf 1 1][e]

[msg MSG_076_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11484 0 0]So ein Glück, ich hatte gehofft, dass du das sagst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ob es in der Bibliothek noch freie Plätze gibt? Ich suche uns welche![n][uf 1 1][e]

[msg MSG_077_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11404 0 0][uf 4 1]-san ... Du bist gekommen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Tut mir leid, ich wollte nicht, dass du mich so siehst, aber na ja ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Wollen wir vielleicht zusammen nach Hause gehen, wenn das in Ordnung ist?[n][uf 1 1][e]

[msg MSG_077_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ähm, wollen wir vielleicht zusammen nach Hause gehen, wenn das in Ordnung ist?[n][uf 1 1][e]

[msg MSG_078_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11434 0 0]Danke. Du bist immer so nett zu mir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Ich will schnell aus der Schule weg. Wollen wir los?[n][uf 1 1][e]

[msg MSG_079_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11404 0 0]Oh, [uf 4 1]-san. Gehst du nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Ich wollte gleich nach dem Unterricht nach Hause. Aber zuerst wollte ich noch hierher ...[n][uf 1 1][e]

[msg MSG_079_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Oh, [uf 4 1]-san. Gehst du nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 0 0]Ich wollte gleich nach dem Unterricht nach Hause. Aber zuerst wollte ich noch hierher ...[n][uf 1 1][e]

[msg MSG_080_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11434 0 0]D-Danke.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0]Mit dir fühle ich mich gleich viel wohler. Wollen wir auf dem Nachhauseweg ein wenig plaudern?[n][uf 1 1][e]

[msg MSG_081_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 1 0][uf 3 1 3 0 65535 11473 0 0]Oh ... H-Hallo, [uf 4 1]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 1 0]Sorry, irgendwie bin ich plötzlich so nervös.[n][uf 1 1][e]

[msg MSG_081_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0]Oh ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 10 65535 65535 1 0]Sorry, irgendwie bin ich plötzlich so nervös.[n][uf 1 1][e]

[msg MSG_082_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11408 0 0]Hallo, [uf 4 1]-san. Gehst du nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Wusstest du, dass der Schülerrat jedes Jahr eine Spendensammlung auf die Beine stellt?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ich bereite die Flyer dafür vor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11454 0 0]Kannst du mir vielleicht dabei helfen, falls du Zeit hast?[n][uf 1 1][e]

[msg MSG_082_5_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Oh, gehst du nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Wusstest du, dass der Schülerrat jedes Jahr eine Spendensammlung auf die Beine stellt?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Ich bereite die Flyer dafür vor.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Kannst du mir vielleicht dabei helfen, falls du Zeit hast?[n][uf 1 1][e]

[msg MND_083_0_0]
[uf 0 5 65278][uf 2 1]Sie will gerade nicht mit mir reden.[n]Ich sollte es ein andermal versuchen.[n][uf 1 1][e]

[msg MSG_084_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]O-Oh, sorry. Es tut mir leid, ich wollte nicht ...[n][uf 1 1][e]

[msg MSG_085_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]O-Oh, sorry. Sicher bist du beschäftigt ...[n][uf 1 1][e]

[msg MSG_086_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]O-Oh, sorry. Natürlich hast du bereits andere Pläne ...[n][uf 1 1][e]

[msg MSG_087_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]Oh, verstehe ... Sicher bist du schon beschäftigt.[n][uf 1 1][e]

[msg MSG_088_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]Oh, sorry, das hätte ich mir denken können. Bis dann.[n][uf 1 1][e]

[msg MSG_089_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]Oh, sorry. Ist schon in Ordnung, wenn du bereits verplant bist ...[n][uf 1 1][e]

[msg MSG_090_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11471 0 0]O-Oh, ich wollte nicht aufdringlich sein. Vielleicht ein andermal ...[n][uf 1 1][e]

[msg MSG_091_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]Oh, sorry. Ich wollte dich nicht stören.[n][uf 1 1][e]

[msg MSG_092_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 3 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]Oh, sorry. Kein Problem. Ich wusste nicht, dass du schon was vorhast.[n][uf 1 1][e]

[msg MSG_093_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 4 65535 65535 0 0][uf 3 1 3 0 65535 11444 0 0]Oh ... Tut mir leid![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Dann vielleicht ein anderes Mal ... Vergiss mich nicht, okay?[n][uf 1 1][e]

[msg MSG_094_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0][uf 3 1 3 0 65535 11472 0 0]Ah, verstehe ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0]Schon in Ordnung. Wann immer es dir passt.[n][uf 1 1][e]

[msg MSG_095_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 0 65535 65535 0 0]Dann eben ein andermal.[n][uf 1 1][e]

[msg MSG_096_0_0 [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1][uf 4 5 109 1 65535 65535 0 0][uf 3 1 3 0 65535 11415 0 0]Bitte komm ruhig zu mir, falls ich dir irgendwie helfen kann.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Chihiro Fushimi]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

