[msg MSG_000_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*mampf, mampf* *mampf, mampf*[n][uf 1 1][e]

[msg MSG_001_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12610 0 0]Hm? Wie? Was willst du?[n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Was isst du da?[e]
[uf 0 5 65278][uf 2 1]Es ist nichts.[e]

[msg MSG_003_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12689 0 0]Spielt das eine Rolle?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Nach diesem Sandwich gehe ich ins nächste Restaurant ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Ahhh, ich bin so was von im Stress ...[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]Das muss der Gourmet-König sein,[n]den Tomochika erwähnt hat ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Mit den Restaurants hier scheint[n]er sich ja auszukennen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich habe wohl nicht so viel [uf 4 30 1 1 1 0] wie sein Sandwich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich muss mindestens [uf 4 31 1 2 1 0] sein, um seine Aufmerksamkeit zu erregen.[n][uf 1 1][e]

[msg MSG_005_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]Oh, na gut ... *mampf, mampf*[n][uf 1 1][e]

[msg MSG_006_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*mampf, mampf* Hm?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]W-Was? Guck mir nicht beim Essen zu.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]Das ist mir unangenehm![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]Du verdirbst mir den Geschmack. So kann ich mein Gourmet-Sandwich nicht genießen ...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]Ich habe genug [uf 4 30 1 1 1 0],[n]um seine Aufmerksamkeit zu erregen.[n][uf 1 1][e]

[msg MSG_008_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12610 0 0]Was willst du?[n][uf 1 1][e]

[sel SEL_009_0_0 top]
[uf 0 5 65278][uf 2 1]Was isst du da?[e]
[uf 0 5 65278][uf 2 1]Es ist nichts.[e]

[msg MSG_010_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12607 0 0]Oh, das interessiert dich? Siehst du dich als Gourmet?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0]Ein Grobian wie du will ein Gourmet sein? Das musst du mir erst beweisen.[n][uf 1 1][e]

[msg MSG_010_5_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12649 0 0]Wenn du mein Gourmetquiz bestehst, dann glaube ich dir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Hmmm, was frage ich dich ...? Es soll ja nicht zu schwer sein.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Lass mich mal nachdenken ...*mampf, mampf*[n][uf 1 1][e]

[msg MSG_011_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]Hmpf. Selber schuld. *mampf, mampf*[n][uf 1 1][e]

[msg MSG_012_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12695 0 0]*schluck*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Wow ... Was für ein Sandwich.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Jetzt fängt das Quiz an. Die erste Frage ist quasi geschenkt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12640 0 0]Was ist das beliebteste Getränk in dem Café da drüben?[n][uf 1 1][e]

[sel SEL_013_0_0 top]
[uf 0 5 65278][uf 2 1]Earl Gray.[e]
[uf 0 5 65278][uf 2 1]Heiße Schokolade mit Sojamilch.[e]
[uf 0 5 65278][uf 2 1]Pheromon-Kaffee.[uf 2 9 1 1 675][e]
[uf 0 5 65278][uf 2 1]Ich muss mich vorbereiten ...[e]

[msg MSG_014_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12677 0 0]Richtig.[n][uf 1 1][e]

[msg MSG_015_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12626 0 0]Bsssst. Falsch. Tut mir leid.[n][uf 1 1][e]

[msg MSG_016_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12649 0 0]Hier kommt Frage 2.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Welche Farbe hat der Rock von Azuki Arais Maskottchen "Azuki-chan"?[n][uf 1 1][e]

[sel SEL_017_0_0 top]
[uf 0 5 65278][uf 2 1]Blau.[e]
[uf 0 5 65278][uf 2 1]Grün.[e]
[uf 0 5 65278][uf 2 1]Rot.[uf 2 9 1 1 676][e]
[uf 0 5 65278][uf 2 1]Ich muss mich vorbereiten ...[e]

[msg MSG_018_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12677 0 0]Hm ... Du hast Ahnung.[n][uf 1 1][e]

[msg MSG_019_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12626 0 0]Bsssst. Falsch. Tut mir leid.[n][uf 1 1][e]

[msg MSG_020_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12649 0 0]Frage 3: Was ist das Geheimgericht auf der Speisekarte im Hagakure?[n][uf 1 1][e]

[sel SEL_021_0_0 top]
[uf 0 5 65278][uf 2 1]Hagakure-Teigtaschen.[e]
[uf 0 5 65278][uf 2 1]Hagakure-Bowl.[uf 2 9 1 1 677][e]
[uf 0 5 65278][uf 2 1]Es gibt keins.[e]
[uf 0 5 65278][uf 2 1]Ich muss mich vorbereiten ...[e]

[msg MSG_022_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12680 0 0]Ich bin beeindruckt ...[n][uf 1 1][e]

[msg MSG_023_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12626 0 0]Bsssst. Falsch. Tut mir leid.[n][uf 1 1][e]

[msg MSG_024_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12640 0 0]Du weißt ein bisschen was über Essen. Aber längst nicht so viel wie ich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Kannst du mir was bringen, was ich noch nie gegessen habe? Wobei das wohl gar nicht existiert.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Wenn du es schaffst, akzeptiere ich dich als gleichgesinnten Gourmet.[n][uf 1 1][e]

[msg MSG_025_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 3 0 65535 12675 0 0]Hm?! W-Was ist das für ein mysteriöses Essen?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0]G-Gib es mir![n][uf 1 1][e]

[msg MND_026_0_0]
[uf 0 5 65278][uf 2 1]Er hat mir etwas genommen ... [uf 4 4 1 37 1 0].[n][uf 1 1][e]

[msg MSG_027_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]Bäh ... das ist ja ... ekelhaft![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Aber ich bin beeindruckt. So was hab ich noch nie gegessen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Du bist nicht übel.[n][uf 1 1][e]

[msg MSG_028_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Oh, du bist es.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Möchtest du mit mir essen? Schließlich hast du mich neulich eingeladen.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Er scheint sich für mich zu interessieren. Soll ich heute mit ihm abhängen?[n][uf 1 1][e]

[sel SEL_030_0_0 top]
[uf 0 5 65278][uf 2 1]Zeit mit ihm verbringen[e]
[uf 0 5 65278][uf 2 1]Jetzt nicht[e]

[msg MSG_031_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12672 0 0]Na schön. Ahhh, ich sterbe vor Hunger ...[n][uf 1 1][e]

[msg MSG_032_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12656 0 0]Hast du etwas gefunden, was ich noch nie gegessen habe? Mir knurrt der Magen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Mit den Gerichten hier in der Gegend brauchst du es gar nicht erst versuchen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Es muss schon außergewöhnlich sein, um meine Erwartungen als Gourmet zu erfüllen.[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]Was er wohl noch nie gegessen hat ...?[n][uf 1 1][e]

[msg MSG_034_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*mampf, mampf* *rülps*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Ich habe keine Lust mehr, dir Fragen zu stellen. Komm wann anders wieder.[n][uf 1 1][e]

[msg MSG_035_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12608 0 0]*schmatz, schmatz* *rülps* Oh, du bist es.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Du bist echt hartnäckig. Willst du wieder den Gourmet-König herausfordern?[n][uf 1 1][e]

[sel SEL_036_0_0 top]
[uf 0 5 65278][uf 2 1]Definitiv.[e]
[uf 0 5 65278][uf 2 1]Nein danke.[e]

[msg MSG_037_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12677 0 0]Dann mach dich bereit![n][uf 1 1][e]

[msg MSG_038_0_0 [Pummeliger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12616 0 0]Oh, alles klar. Bis dann. *mampf, mampf*[n][uf 1 1][e]

[msg MSG_039_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12607 0 0]*schmatz, schmatz* *rülps* Hallo, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz bitterlich.[n][uf 1 1][e]

[msg MSG_040_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12607 0 0]*schmatz, schmatz* *rülps* Hallo, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Wunderst du dich, was ich anhabe?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Tja, weißt du, ich trage unsere Schuluniform, weil ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 4 25 116]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12689 0 0]... mir sonst nichts anderes passt![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 4 25 116]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Egal, wollen wir was essen gehen? Mein armer Magen weint schon ganz lange.[n][uf 1 1][e]

[msg MND_041_0_0]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit[n]mit Suemitsu verbringen?[n][uf 1 1][e]

[msg MND_042_0_0]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit Suemitsu verbringen?[n][uf 1 1][e]

[sel SEL_043_0_0 top]
[uf 0 5 65278][uf 2 1]Zeit mit ihm verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link-Status anzeigen[e]
[uf 0 5 65278][uf 2 1]Jetzt nicht[e]

[msg MSG_044_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, meine Gourmet-Freundin.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Beginnen wir unser epikureisches Abenteuer! Ich weiß auch schon, wo.[n][uf 1 1][e]

[msg MSG_045_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12641 0 0]Ohh! Ich hätte dich auf ein kulinarisches Abenteuer entführt![n][uf 1 1][e]

[msg MSG_046_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*mampf* *schmatz, schmatz* Ah, ja.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz bitterlich.[n][uf 1 1][e]

[msg MSG_047_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schluck*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Wunderst du dich, was ich anhabe?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Tja, weißt du, ich trage unsere Schuluniform, weil ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 4 25 116]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12689 0 0]... mir sonst nichts anderes passt![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 4 25 116]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz bitterlich.[n][uf 1 1][e]

[msg MSG_048_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*mampf, mampf* Endlich sind die Prüfungen vorbei. Jetzt wird geschlemmt![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Jede Prüfung war eine Tortur! Ich brauche Nervennahrung *mampf, mampf*[n][uf 1 1][e]

[msg MSG_049_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12640 0 0]Hattest du während der Prüfungen auch solchen Hunger, [uf 4 1]-chan. Ein Gourmet muss schließen essen.[n][uf 1 1][e]

[msg MSG_050_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*mampf* Ah, richtig.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz bitterlich.[n][uf 1 1][e]

[msg MSG_050_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, mein kulinarischer Freund. Beginnen wir unser epikureisches Abenteuer![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Heute gibt es in der Einkaufsstraße saftiges Fleisch, eine förmliche Geschmacksexplosion. Und damit kann nur ein Ort gemeint sein.[n][uf 1 1][e]

[msg MSG_051_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12608 0 0]*schmatz, schmatz* *rülps* Oh, hey, [uf 4 2]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz jämmerlich.[n][uf 1 1][e]

[msg MSG_051_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Ah, richtig.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz jämmerlich.[n][uf 1 1][e]

[msg MSG_052_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, meine Gourmet-Freundin! Mal sehen ... Letztes Mal waren wir im Fleischparadies.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Ich weiß, wo wir hin können.[n][uf 1 1][e]

[msg MSG_053_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12602 0 0]*schmatz, schmatz* *rülps* Hallöchen, [uf 4 2]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz bitterlich.[n][uf 1 1][e]

[msg MSG_053_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Ah, richtig.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen weint schon ganz bitterlich.[n][uf 1 1][e]

[msg MSG_054_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, meine Gourmet-Freundin! Unser kulinarisches Abenteuer geht weiter![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Heute gehen wir zu Wakatsu. Das Menü hat für alle etwas zu bieten.[n][uf 1 1][e]

[msg MSG_055_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12609 0 0]*schmatz, schmatz* *rülps* Wenn das nicht [uf 4 2]-chan ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen heischt nach Aufmerksamkeit.[n][uf 1 1][e]

[msg MSG_055_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Ah, richtig.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Perfektes Timing. Wollen wir was essen gehen? Mein armer Magen heischt nach Aufmerksamkeit.[n][uf 1 1][e]

[msg MSG_056_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, meine Gourmet-Freundin![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Wonach gelüstet dich heute? Reis? Sandwiches? Oder Nudeln? Da weiß ich was![n][uf 1 1][e]

[msg MSG_057_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12609 0 0]*schmatz, schmatz* *rülps* Ahhh, da bist du ja endlich, [uf 4 2]-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]Wollen wir was essen gehen? Mein armer Magen weint schon ganz kläglich.[n][uf 1 1][e]

[msg MSG_057_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Ahhh![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]Wollen wir was essen gehen? Mein armer Magen weint schon ganz kläglich.[n][uf 1 1][e]

[msg MSG_058_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, meine Gourmet-Freundin. Ich wusste, ich kann auf dich zählen, [uf 4 2]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Und das heutige Hauptgericht ist ... Fischsuppe! Dafür kenne ich die perfekte Lokalität.[n][uf 1 1][e]

[msg MSG_059_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12602 0 0]*schmatz, schmatz* *rülps* Oh, hey, [uf 4 2]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Wollen wir was essen gehen? Mein Magen grummelt schon rachsüchtig.[n][uf 1 1][e]

[msg MSG_059_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Oh, stimmt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Wollen wir was essen gehen? Mein Magen grummelt schon rachsüchtig.[n][uf 1 1][e]

[msg MSG_060_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, meine Gourmet-Freundin![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0]Ehrlich gesagt, wollte ich heute mit dir reden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Suchen wir uns also ein Plätzchen, wo man schlemmen und plaudern kann. Dafür kenne ich die perfekte Lokalität![n][uf 1 1][e]

[msg MSG_061_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12604 0 0]*schmatz, schmatz* *rülps* Oh, [uf 4 2]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]Können wir reden? Mein Magen schluchzt vor Trauer, doch darum geht es jetzt nicht.[n][uf 1 1][e]

[msg MSG_061_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Öhm ... also...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]Können wir reden? Mein Magen schluchzt vor Trauer, doch darum geht es jetzt nicht.[n][uf 1 1][e]

[msg MSG_062_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, mein Gourmet-Fr...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]Ähm, nein. Heute essen wir nichts. Heute wird geredet ...[n][uf 1 1][e]

[msg MSG_063_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12605 0 0]*schmatz, schmatz* *rülps* Oh, [uf 4 2]-chan![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Ich habe dich erwartet. Mein Magen knurrt unbändig.[n][uf 1 1][e]

[msg MSG_063_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 0 65535 65535 0 0][uf 3 1 3 0 65535 12697 0 0]*schmatz, schmatz* *rülps* Oh, stimmt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Ich habe dich erwartet. Mein Magen knurrt unbändig.[n][uf 1 1][e]

[msg MSG_064_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12667 0 0]Wunderbar, meine Gourmet-Freundin![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 1 65535 65535 0 0]Zuerst muss ich dir etwas erzählen! Danach, hm ... Oh, da kenn ich die perfekte Lokalität![n][uf 1 1][e]

[msg MSG_065_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12665 0 0]Oh, [uf 4 2]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0]H-Hey, ähhh, ähm, äh, alsoooo ...[n][uf 1 1][e]

[msg MSG_065_5_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12692 0 0]H-Hey, ähhh, ähm, äh, alsoooo ...[n][uf 1 1][e]

[msg MSG_066_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 4 65535 65535 0 0][uf 3 1 3 0 65535 12663 0 0]W-Wirklich?[n][uf 1 1][e]

[msg MND_067_0_0]
[uf 0 5 65278][uf 2 1]Jetzt kann ich nichts tun ... Ich sollte an einem anderen Tag mit ihm reden.[n][uf 1 1][e]

[msg MSG_172_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12671 0 0]Ohh! Ich hätte dich auf ein kulinarisches Abenteuer entführt![n][uf 1 1][e]

[msg MSG_173_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12671 0 0]Ohh! Ich hätte dich auf ein kulinarisches Abenteuer entführt![n][uf 1 1][e]

[msg MSG_174_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12671 0 0]Ohh! Und was ist mit unserem kulinarischen Abenteuer?![n][uf 1 1][e]

[msg MSG_175_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 2 65535 65535 0 0][uf 3 1 3 0 65535 12670 0 0]Wieee!? Und was ist mit unserem kulinarischen Abenteuer?![n][uf 1 1][e]

[msg MSG_176_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12671 0 0]Ohh! Ich wollte doch ein kulinarisches Abenteuer mit dir erleben.[n][uf 1 1][e]

[msg MSG_177_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12671 0 0]Oh ... Dann muss unser kulinarisches Abenteuer wohl warten.[n][uf 1 1][e]

[msg MSG_178_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12687 0 0]Wie?! Gehst du etwa nur mit auf unser kulinarisches Abenteuer, wenn das Essen köstlich ist?![n][uf 1 1][e]

[msg MSG_179_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12675 0 0]Was?! Ich hätte dich auf ein kulinarisches Abenteuer entführt![n][uf 1 1][e]

[msg MSG_180_0_0 [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1][uf 4 5 116 3 65535 65535 0 0][uf 3 1 3 0 65535 12695 0 0]O-Oh ... Schon in Ordnung ...[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Nozomi Suemitsu]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

