[msg MSG_000_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11265 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich gehe jetzt zum Club. Was machst du?[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Unused[n][uf 1 1][e]

[msg MSG_002_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11204 0 0][uf 4 1]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Schaffst du es heute zum Kunstclub? Ich würde mich freuen.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit beim Kunstclub verbringen?[n][uf 1 1][e]

[sel SEL_004_0_0 top]
[uf 0 5 65278][uf 2 1]Zum Kunstclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link-Status anzeigen[e]
[uf 0 5 65278][uf 2 1]Jetzt nicht[e]

[msg MSG_005_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11293 0 0]Oh, dann gehen wir zusammen.[n][uf 1 1][e]

[msg MSG_006_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Unused[n][uf 1 1][e]

[msg MSG_007_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 4 65535 65535 0 0]Unused[n][uf 1 1][e]

[msg MND_008_0_0]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_009_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11246 0 0]Oh, okay ... dann bis irgendwann.[n][uf 1 1][e]

[msg MSG_010_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, stimmt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich gehe jetzt zum Club. Was machst du?[n][uf 1 1][e]

[msg MSG_011_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Unused[n][uf 1 1][e]

[msg MSG_012_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, da fällt mir ein ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Schaffst du es heute zum Kunstclub? Ich würde mich freuen.[n][uf 1 1][e]

[msg MSG_013_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11202 0 0]Oh, [uf 4 1]-chan. Wie lief es für dich mit den Prüfungen?[n][uf 1 1][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0]Jedenfalls haben wir jetzt wieder mehr Zeit für den Kunstclub.[n][uf 1 1][e]

[msg MSG_015_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0]Jedenfalls sind wir endlich fertig. Diesmal hab ich echt gebüffelt.[n][uf 1 1][e]

[msg MSG_016_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11201 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich gehe jetzt zum Club. Was machst du heute noch?[n][uf 1 1][e]

[msg MSG_016_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, stimmt. Ich gehe jetzt zum Club. Was machst du heute noch?[n][uf 1 1][e]

[msg MSG_017_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11223 0 0]Großartig! Dann los.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0]Zeichne erst mal, was du willst. Falls du Fragen hast, gibt Bescheid.[n][uf 1 1][e]

[msg MSG_018_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11212 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Bin gerade erst angekommen. Kommst du heute zum Kunstclub?[n][uf 1 1][e]

[msg MSG_018_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Übrigens, kommst du heute zum Kunstclub?[n][uf 1 1][e]

[msg MSG_019_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11293 0 0]Super! Dann sehen wir uns dort.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, stimmt ... Ich wollte dem Clubberater noch von dir erzählen.[n][uf 1 1][e]

[msg MSG_020_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11265 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Kommst du heute zum Club? Wir sollten uns über die Zukunft unterhalten ...[n][uf 1 1][e]

[msg MSG_020_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Oh, kommst du heute zum Club? Wir sollten uns über die Zukunft unterhalten ...[n][uf 1 1][e]

[msg MSG_021_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11219 0 0]Okay, gehen wir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Reden wir später. Alle warten schon auf uns.[n][uf 1 1][e]

[msg MSG_022_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11201 0 0]Oh, [uf 4 1]-chan, schaffst du es heute zum Kunstclub?[n][uf 1 1][e]

[msg MSG_022_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Übrigens, gehst du heute zum Kunstclub?[n][uf 1 1][e]

[msg MSG_023_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11219 0 0]Super, Wir sehen uns dort.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]Wenn das so ist ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, nicht so wichtig. Konzentrieren wir uns auf die Kunst.[n][uf 1 1][e]

[msg MSG_024_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11263 0 0][uf 4 1]-chan. Gehst du zum Kunstclub?[n][uf 1 1][e]

[msg MSG_024_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, stimmt. Gehst du zum Kunstclub?[n][uf 1 1][e]

[msg MSG_025_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11219 0 0]Großartig! Wir sehen uns dort.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11252 0 0][uf 4 25 108]......[n][uf 1 1][e]

[msg MSG_026_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11202 0 0]Oh, [uf 4 1]-chan, schaffst du es heute zum Kunstclub?[n][uf 1 1][e]

[msg MSG_026_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Oh, [uf 4 1]-chan, schaffst du es heute zum Kunstclub?[n][uf 1 1][e]

[msg MSG_027_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11293 0 0]Okay, Dann sehen wir uns dort.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0]*gähn* Ich bin ein bisschen erschöpft ...[n][uf 1 1][e]

[msg MSG_028_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11234 0 0]Danke. Eigentlich dachte ich gerade an ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0]Ist nicht so wichtig. Reden wir später darüber. Zuerst sollte ich nach allen sehen.[n][uf 1 1][e]

[msg MSG_029_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11261 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich muss euch allen heute etwas sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Als Clubleiter fände ich es schön, wenn du auch kommst.[n][uf 1 1][e]

[msg MSG_029_5_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Hey, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich muss euch allen heute etwas sagen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Als Clubleiter fände ich es schön, wenn du auch kommst.[n][uf 1 1][e]

[msg MSG_030_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 3 0 65535 11232 0 0]Danke.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Alle anderen sollten schon da sein, lass uns also erst mal zeichnen.[n][uf 1 1][e]

[msg MSG_031_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_032_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11246 0 0]Bist du beschäftigt? Dann vielleicht nächstes Mal.[n][uf 1 1][e]

[msg MSG_033_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1]Unused[n][uf 1 1][e]

[msg MSG_034_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11246 0 0]Oh, na gut. Sei vorsichtig auf dem Heimweg.[n][uf 1 1][e]

[msg MSG_035_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11246 0 0]Oh, bist du beschäftigt? Komm jederzeit gerne vorbei.[n][uf 1 1][e]

[msg MSG_036_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11246 0 0]Oh, tut mir leid, das zu hören. Vielleicht ja nächstes Mal.[n][uf 1 1][e]

[msg MSG_037_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11214 0 0]Oh, hast du schon was vor? Dann sehen wir uns später.[n][uf 1 1][e]

[msg MSG_038_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 3 65535 65535 0 0][uf 3 1 3 0 65535 11290 0 0]O-Oh ... Dann klappt es heute wohl nicht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Sorry, ich führe bloß Selbstgespräche. Du gehst nach Hause, oder? Pass auf dich auf.[n][uf 1 1][e]

[msg MSG_039_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 3 0 65535 11214 0 0]Tja, da kann man nichts machen. Dann nächstes Mal.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

