[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1093 0 0]Gehst du nach Hause, [uf 4 1]-chan?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Gehen wir zusammen nach Hause.[e]
[uf 0 5 65278][uf 2 1]Jepp. Bis dann.[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1028 0 0]Ähm ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]N-Nein Danke. Vielleicht nächstes Mal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Sorry, mir ist gerade nicht danach. Mir fehlen ein wenig die Worte.[n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Yukari will wohl über etwas reden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich sollte an meinem [uf 4 30 1 1 1 0] arbeiten, wenn sie sich mir gegenüber öffnen soll.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Wäre ich [uf 4 31 1 6 1 0], würde sie mit mir über ihre Probleme reden ...[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1023 0 0]Oh, okay. Bis dann.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, [uf 4 1]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1077 0 0]Könnten wir miteinander reden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Ähm ... irgendwo, wo es ungestört ist?[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Mein [uf 4 30 1 1 1 0] flößt Yukari Vertrauen ein.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Das ist meine Chance, sie besser kennenzulernen.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Also, äh ... können wir aufs Dach gehen?[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Klar.[e]
[uf 0 5 65278][uf 2 1]Ich kann heute nicht.[e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1042 0 0]Danke, ich wollte mit dir reden.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Gut, dann los.[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh ... okay... Dann vielleicht ein andermal.[n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Gehst du allein nach Hause? Dann komme ich mit.[n][uf 1 1][e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Yukari möchte mit mir nach Hause gehen.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Hey, [uf 4 1]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0][uf 3 1 3 0 65535 1077 0 0]Bitte entschuldige wegen neulich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Ähm, hast du jetzt gerade Zeit? Ich würde gerne mit dir darüber reden.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit Yukari verbringen?[n][uf 1 1][e]

[sel SEL_015_0_0 top]
[uf 0 5 65278][uf 2 1]Zeit mit ihr verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link-Status anzeigen[e]
[uf 0 5 65278][uf 2 1]Jetzt nicht[e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1025 0 0]Super! Gehen wir irgendwohin![n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1042 0 0]D-Danke ...[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Wollen wir aufs Dach gehen?[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1110 0 0]Wenn das so ist ...[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 1 0]Willst du ... mit auf mein Zimmer kommen?[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 1 0][uf 3 1 3 0 65535 1025 0 0]Wie ...? K-Klar ... okay.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 1 0]Also ... willst du mit auf mein Zimmer kommen?[n][uf 1 1][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1053 0 0]Oh, bist du beschäftigt? Na ja, vielleicht ein andermal.[n][uf 1 1][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1089 0 0][uf 4 25 2]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]W-Was willst du denn?[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Schon wieder ...?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Spuck's aus, wenn du was sagen willst.[n][uf 1 1][e]

[sel SEL_025_0_0 top]
[uf 0 5 65278][uf 2 1]Gehen wir zusammen nach Hause.[e]
[uf 0 5 65278][uf 2 1]Es tut mir leid.[e]
[uf 0 5 65278][uf 2 1]Es war nichts.[e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1123 0 0]Also schön ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich war wohl auch etwas grob, tut mir leid.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Vielleicht können wir mal wieder was unternehmen ...[n][uf 1 1][e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Wir beide haben uns versöhnt![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich sollte bei nächster Gelegenheit mit ihr was unternehmen.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1124 0 0][uf 4 25 2]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Ich glaube, du meinst das gar nicht ernst ...[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Yukari ist immer noch abweisend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ich sollte in ein paar Tagen wieder mit ihr reden, um unsere Beziehung zu kitten.[n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 3 0 65535 1049 0 0]Ach, wirklich?[n][uf 1 1][e]

[msg MSG_031_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Ich dachte, du hättest nichts zu sagen.[n][uf 1 1][e]

[msg MSG_032_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Alles wieder gut, danke.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Ich bin auch für dich da, vergiss das ja nicht, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 0 0 0 0 0 0][uf 4 25 2]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 1 0][uf 3 1 3 0 65535 1111 0 0]S-Starr mich nicht so an ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 1 0]Falls uns jemand sieht, gibt es Gerüchte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 1 0][uf 3 1 0 0 0 0 0 0][uf 4 25 2]......[n][uf 1 1][e]

[msg MND_033_0_0]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und Yukari.[n][uf 1 1][e]

[msg MSG_034_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]未使用メッセージだよ。
[n][uf 1 1][e]

[msg MSG_035_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Super, dann lass uns fenstershoppen! Vielleicht gibt's was Neues![n][uf 1 1][e]

[msg MSG_036_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Mir geht es wieder gut. Zum Glück habe ich dich und die anderen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Ich wir sind alle für dich da. Vergiss das ja nicht, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Schluck deine Probleme nicht einfach runter, in Ordnung?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1095 0 0]Falls du je Hilfe brauchst, kannst du auf uns zählen.[n][uf 1 1][e]

[msg MND_037_0_0]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und Yukari.[n][uf 1 1][e]

[msg MSG_038_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Wolltest du eigentlich gerade nach Hause?[n][uf 1 1][e]

[msg MSG_039_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Könnten wir miteinander reden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Ähm ... irgendwo, wo es ungestört ist?[n][uf 1 1][e]

[msg MSG_040_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, da fällt mir ein ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Gehst du allein nach Hause? Dann komme ich mit.[n][uf 1 1][e]

[msg MSG_041_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0]H-Hey, wegen neulich ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Ähm, hast du jetzt gerade Zeit? Ich würde gerne mit dir darüber reden.[n][uf 1 1][e]

[msg MSG_042_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Oh, hey, [uf 4 1]-chan. Endlich sind die Prüfungen vorbei.[n][uf 1 1][e]

[msg MSG_043_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ganz schön erleichternd, oder?[n][uf 1 1][e]

[msg MSG_044_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Ich bin von all der Paukerei noch ganz platt, du bestimmt auch. Wir können uns gegenseitig auf die Schultern klopfen.[n][uf 1 1][e]

[msg MSG_045_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Puh, endlich können wir durchatmen. Wir sollten stolz auf uns sein.[n][uf 1 1][e]

[msg MSG_046_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]Super! Dann lass uns was unternehmen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Stimmt ... Eines wollte ich ausprobieren.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Suchst du was Schönes mit mir aus?[n][uf 1 1][e]

[msg MSG_047_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1075 0 0]Wollen wir auf dem Nachhauseweg noch beim Paulownia-Einkaufszentrum vorbeischauen?[n][uf 1 1][e]

[msg MSG_047_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Oh, hey! Wollen wir auf dem Nachhauseweg noch beim Paulownia-Einkaufszentrum vorbeischauen?[n][uf 1 1][e]

[msg MSG_048_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1025 0 0]Okay, dann los.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich wollte kurz was shoppen und dann in den Musikladen ...[n][uf 1 1][e]

[msg MSG_049_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Ich wollte heute noch ins Paulownia-Einkaufszentrum. Kommst du mit?[n][uf 1 1][e]

[msg MSG_049_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich wollte heute noch ins Paulownia-Einkaufszentrum. Kommst du mit?[n][uf 1 1][e]

[msg MSG_050_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1039 0 0]Cool! Los geht's![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Wolltest du noch irgendwohin? Sonst könnten wir zuerst Tee trinken und danach shoppen.[n][uf 1 1][e]

[msg MSG_051_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Na du? Gehst du jetzt nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich wollte noch in der Einkaufsstraße vorbeischauen. Lust, mitzukommen?[n][uf 1 1][e]

[msg MSG_051_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, gehst du jetzt nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich wollte noch in der Einkaufsstraße vorbeischauen. Lust, mitzukommen?[n][uf 1 1][e]

[msg MSG_052_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1087 0 0]Gut, dann lass uns los![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Mir ist nicht nach Ramen ... Was gibt es sonst noch?[n][uf 1 1][e]

[msg MSG_053_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1114 0 0]Endlich bin ich fertig ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Ich habe die ganze Mittagspause damit verbracht, im Bogenschießenclub aufzuräumen, jetzt knurrt mein Magen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Vielleicht gehe ich auf dem Rückweg zu Wakatsu oder so ...[n][uf 1 1][e]

[msg MSG_053_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Heute bin ich total im Stress ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Ich habe die ganze Mittagspause damit verbracht, im Bogenschießenclub aufzuräumen, jetzt knurrt mein Magen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Vielleicht gehe ich auf dem Rückweg zu Wakatsu oder so ...[n][uf 1 1][e]

[msg MSG_054_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]Haha, danke. Ich esse ungern allein, weißt du?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Gut, dann legen wir los! Hmmm, was soll ich bestellen ...[n][uf 1 1][e]

[msg MSG_055_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh, hallo, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1002 0 0]Willst du schon nach Hause? Wir könnten was zusammen unternehmen.[n][uf 1 1][e]

[msg MSG_055_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Willst du eigentlich schon nach Hause? Wir könnten was zusammen unternehmen.[n][uf 1 1][e]

[msg MSG_056_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]Oh, du kommst mit? Super![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Hmm ... Gehen wir ins Paulownia-Einkaufszentrum. Ich wollte mir ein paar Sachen ansehen.[n][uf 1 1][e]

[msg MSG_057_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1004 0 0]Hey, [uf 4 1]-chan. Gehst du nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 1 0]Ähm ... Hast du vielleicht Zeit zu reden?[n][uf 1 1][e]

[msg MSG_057_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Oh ... Gehst du nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 1 0]Ähm ... Hast du vielleicht Zeit zu reden?[n][uf 1 1][e]

[msg MSG_058_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1042 0 0]Danke.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Aber lass uns nicht hierbleiben ... Gehen wir aufs Dach.[n][uf 1 1][e]

[msg MSG_059_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Oh ... [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Ähm ... Bist du gerade beschäftigt?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Ist nicht so wichtig, aber ... ich muss dir etwas sagen.[n][uf 1 1][e]

[msg MSG_059_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ähm ... Bist du gerade beschäftigt?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Ist nicht so wichtig, aber ... ich muss dir etwas sagen.[n][uf 1 1][e]

[msg MSG_060_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1113 0 0]Super, wenn das so ist ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Gehen wir aufs Dach. Es dauert auch nicht lang.[n][uf 1 1][e]

[msg MSG_061_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1010 0 0]Oh, hallo.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich wollte gerade nach Hause. Und du?[n][uf 1 1][e]

[msg MSG_061_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Oh, ich wollte gerade nach Hause. Und du?[n][uf 1 1][e]

[msg MSG_062_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Hey, was geht?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich schaue auf dem Weg nach Hause im Paulownia-Einkaufszentrum vorbei. Willst du mitkommen?[n][uf 1 1][e]

[msg MSG_062_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Oh, stimmt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich schaue auf dem Weg nach Hause im Paulownia-Einkaufszentrum vorbei. Willst du mitkommen?[n][uf 1 1][e]

[msg MSG_166_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1020 0 0]Oh, wie schade. Dann bis später.[n][uf 1 1][e]

[msg MSG_167_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Oh, na gut. Dann bis später.[n][uf 1 1][e]

[msg MSG_168_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1020 0 0]Oh, bist du beschäftigt? Dann vielleicht nächstes Mal.[n][uf 1 1][e]

[msg MSG_169_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1021 0 0]Oh, es passt wohl gerade nicht. Dann bis später.[n][uf 1 1][e]

[msg MSG_170_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0][uf 3 1 3 0 65535 1094 0 0]Oh, okay ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Das kam wohl zu plötzlich, sorry. Dann sehen wir uns später.[n][uf 1 1][e]

[msg MSG_171_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1020 0 0]Oh, wie schade. Vielleicht nächstes Mal.[n][uf 1 1][e]

[msg MSG_172_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1020 0 0]Oh, hast du schon was vor? Dann vielleicht nächstes Mal.[n][uf 1 1][e]

[msg MSG_173_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1110 0 0]Oh, vielleicht ja nächstes Mal. Dann bis später.[n][uf 1 1][e]

[msg MSG_174_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1020 0 0]Ich habe all meinen Mut zusammengenommen, um dich einzuladen. Tja, vielleicht nächstes Mal.[n][uf 1 1][e]

[msg MSG_175_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1020 0 0]Oh, hattest du schon was vor? Dann vielleicht nächstes Mal.[n][uf 1 1][e]

[msg MSG_176_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Oh, okay, dann sehen wir uns im Wohnheim.[n][uf 1 1][e]

[msg MSG_177_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 65535 65535 0 0]W-Was? Für heute sollten wir fertig sein.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Vielleicht ein andermal.[n][uf 1 1][e]

[msg MSG_178_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1021 0 0]In Ordnung, dann sehen wir uns später wieder im Wohnheim. Du kannst immer zu mir kommen.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

