[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Heute Morgen war ich in der Monorail etwas nervös.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Unser Kampf hätte auch anders ausgehen können. Es war verdammt knapp ...[n][uf 1 1][e]

[msg MSG_001_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Oh, [uf 4 1]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Weißt du, diese Gerüchte sind schon gruselig.[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Hast du was über die Geistergeschichte herausgefunden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Ich beweise allen, dass das nur ein Gerücht war.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Und ich habe keine Angst, okay?![n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Hey, [uf 4 1]-chan, du denkst an heute, oder?[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 3 0 65535 1093 0 0]Yamagishi-san ist wohl immer noch bewusstlos.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Ich sorge mich unentwegt um sie ...[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1115 0 0]Yamagishi-san kommt bald aus dem Krankenhaus. Ist das nicht super?[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Zum Glück ist jetzt eine Weile lang kein Vollmond, aber trotzdem ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich muss ständig daran denken.[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1028 0 0][uf 4 1]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Ich begreife es immer noch nicht. Ich hab schon Kopfweh vom Nachdenken.[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1089 0 0]Ich habe gründlich nachgedacht, [uf 4 1]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0]Ich glaube, wir haben keine andere Wahl. Wir müssen es machen.[n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1114 0 0]Bald haben wir Prüfungen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Die im dritten Jahr haben was auf dem Kasten. Wir brauchen also gute Noten, sonst lachen sie uns aus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Hm ... vielleicht lerne ich in der Bibliothek. Ich werde immer so müde, wenn ich abends noch lerne ...[n][uf 1 1][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1095 0 0]Puh ... Endlich sind die Prüfungen vorbei.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Die waren soooo schwer! Jetzt will ich nur noch abschalten![n][uf 1 1][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, [uf 4 1]-chan. Ich hab die Ergebnisse gesehen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Na ja ... ist schon okay. Noten sind nicht alles, oder?[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, [uf 4 1]-chan. Ich hab die Ergebnisse gesehen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Du hattest wohl keinen guten Tag, oder? Hätte besser laufen können.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich hab die Ergebnisse gesehen. Du hast dich gut geschlagen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Unsere Senpais dürfte das freuen.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich hab die Ergebnisse gesehen. Du warst weit oben auf der Liste![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Kirijo-senpai war beeindruckt. Vielleicht belohnt sie dich ja irgendwie ...[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich hab die Ergebnisse gesehen. Du warst weit oben auf der Liste![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Mitsuru-senpai war beeindruckt. Vielleicht belohnt sie dich ja irgendwie ...[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1073 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Ich hab die Ergebnisse gesehen. Du stehst an der Spitze, unglaublich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Kirijo-senpai ist garantiert beeindruckt. Vielleicht belohnt sie dich ja irgendwie ...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1073 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0]Ich hab die Ergebnisse gesehen. Du stehst an der Spitze, unglaublich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Mitsuru-senpai ist garantiert beeindruckt. Vielleicht belohnt sie dich ja irgendwie ...[n][uf 1 1][e]

[msg MSG_018_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1074 0 0]Hast du gehört, dass der Kunstclub neue Mitglieder annimmt?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]War Fuuka nicht im Kunstclub?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Vielleicht solltest du da mal reinschnuppern. Gucken, wie es da so läuft und so.[n][uf 1 1][e]

[msg MSG_019_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, [uf 4 1]-chan.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1074 0 0]Du bist jetzt also im Leichtathletikteam? Sie meinten, du hast viel Potenzial.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Ich bin im Bogenschießenclub. Geben wir beide unser Bestes, okay?[n][uf 1 1][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Hey, [uf 4 1]-chan. Gehst du nach Hause?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich dachte, es interessiert dich, dass das Leichtathletikteam neue Mitglieder annimmt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Die haben einen ziemlich guten Ruf. Das könntest du dir mal ansehen.[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Oh, so ein Zufall. Shoppst du auch gerade, [uf 4 1]-chan?[n][uf 1 1][e]

[sel SEL_022_0_0 top]
[uf 0 5 65278][uf 2 1]Ganz genau.[e]
[uf 0 5 65278][uf 2 1]Ich spaziere nur herum.[e]

[msg MSG_023_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1095 0 0]In diesem Einkaufszentrum bekommt man fast alles.[n][uf 1 1][e]

[msg MSG_024_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1025 0 0]Sich in seiner Stadt auszukennen, ist nie verkehrt.[n][uf 1 1][e]

[msg MSG_025_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1067 0 0]Oh, hey, du bist ja ganz alleine hier. Na ja, ich aber auch.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich hänge gerne mit Freunden ab, aber manchmal brauche ich auch Zeit für mich.[n][uf 1 1][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1072 0 0]Oh, [uf 4 1]-chan ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1119 0 0]Der Sommer nimmt Fahrt auf, ist das heiß.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Morgen fängt die Sommerschule an, darum will ich die freie Zeit heute noch mal nutzen![n][uf 1 1][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Wir haben fast Mai. Da ist es nicht immer leicht, sich passend anzuziehen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Manchmal ist es schon heiß, aber dann wird es plötzlich wieder kalt.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Darum sind die Schuluniformen so praktisch. Außerdem lassen sie sich individuell anpassen.[n][uf 1 1][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0]Koro-chan ist der Hammer! Er war neulich so mutig! Ich weiß nicht, wie er so geworden ist, aber er ist unglaublich![n][uf 1 1][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1119 0 0]Schon wieder so heiß. Man kriegt schon einen Hitzschlag, wenn man nur draußen steht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0]Ich muss schnell weiter shoppen, damit ich nach Hause kann.[n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1001 0 0]Und ... bist du mit deinen Hausaufgaben fertig?[n][uf 1 1][e]

[sel SEL_031_0_0 top]
[uf 0 5 65278][uf 2 1]Ja.[e]
[uf 0 5 65278][uf 2 1]Nein.[e]
[uf 0 5 65278][uf 2 1]Ich hab's vergessen.[e]

[msg MSG_032_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1107 0 0]Wow, nicht schlecht! Du bist verantwortungsbewusst, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_033_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1110 0 0]Argh ... Dann setzt dich lieber schnell dran. Ich bin auch noch nicht fertig.[n][uf 1 1][e]

[msg MSG_034_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Das kauft der Lehre dir nicht ab. Er wird dich bloß nachsitzen lassen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Und dann kannst du nicht in den Tartarus. Erledige es also lieber gleich.[n][uf 1 1][e]

[msg MSG_035_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1075 0 0]Ich gehe später mit einer Freundin ins Kino. Der Film läuft heute erst an.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Allerdings ist sie ganz schön spät dran. Wo bleibt sie nur?[n][uf 1 1][e]

[msg MSG_036_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Ich wollte mir einen Badeanzug kaufen, aber keiner gefällt mir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Warum wohl? Ich habe nichts gegen die Auswahl.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0]Vielleicht bin ich bloß nicht in Shoppinglaune.[n][uf 1 1][e]

[msg MSG_037_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1061 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ist dir aufgefallen, dass sich Sanada-senpai in Amada-kuns Nähe anders verhält?[n][uf 1 1][e]

[sel SEL_038_0_0 top]
[uf 0 5 65278][uf 2 1]Unused[e]
[uf 0 5 65278][uf 2 1]Irgendwie schon.[e]

[msg MSG_039_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1062 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Warum wohl ...? Vielleicht mag er einfach keine Kinder. Er wirkt ein wenig unbeholfen.[n][uf 1 1][e]

[msg MSG_040_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1022 0 0]Unused[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Übersiehst du so was einfach? Jedenfalls frage ich mich, woran das liegt. Sonst ist er nicht so.[n][uf 1 1][e]

[msg MSG_041_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1078 0 0]Oh, [uf 4 1]-chan. Darf ich vorstellen? Das ist Ken-kun.[n][uf 1 1][e]

[msg MSG_042_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Freut mich, dich kennenzulernen. Ich bin Ken Amada.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Bist du mit Yukari-san und Junpei-san befreundet?[n][uf 1 1][e]

[msg MSG_043_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Du hast es erfasst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Er wohnt im selben Wohnheim wie Yuka-tan und ich.[n][uf 1 1][e]

[msg MSG_044_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 4 65535 65535 0 0]Wirklich? Ich wusste nicht, dass es Wohnheime gibt, in denen sowohl Mädchen als auch Jungs leben.[n][uf 1 1][e]

[msg MSG_045_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 1]Ähm, also, na ja ... Es ist ...[n][uf 1 1][e]

[msg MSG_046_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0]Wir sind eine Ausnahme! Es gibt gute Gründe dafür, dass wir zusammen wohnen ...[n][uf 1 1][e]

[msg MSG_047_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 3 65535 65535 0 0]M-hm ...[n][uf 1 1][e]

[msg MSG_048_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 3 0 65535 1131 0 0]In letzter Zeit habe ich viel mit Amada-kun zu tun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Er ist erstaunlich zuverlässig, und so viel reifer als Dummpei.[n][uf 1 1][e]

[msg MSG_049_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 3 0 65535 1009 0 0]Oh. Hey, [uf 4 1]-chan.[n][uf 1 1][e]

[msg MSG_050_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 0 65535 65535 0 0]Hallo, [uf 4 1]-san.[n][uf 1 1][e]

[msg MSG_051_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich habe gerade wieder mit Amada-kun geredet. Besuchst du ihn auch hier?[n][uf 1 1][e]

[sel SEL_052_0_0 top]
[uf 0 5 65278][uf 2 1]Ganz genau.[e]
[uf 0 5 65278][uf 2 1]Ich bin deinetwegen hier, Yukari.[e]

[msg MSG_053_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 11 65535 65535 0 0][uf 3 1 3 0 65535 1132 0 0]Ist das nicht super, Amada-kun? [uf 4 1]-chan will auch dein Freund sein.[n][uf 1 1][e]

[msg MSG_054_0_0 [Ken Amada]]
[uf 0 5 65278][uf 2 1][uf 4 5 8 1 65535 65535 0 0]Danke fürs Kommen![n][uf 1 1][e]

[msg MSG_055_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1052 0 0]Echt ...? Aber wir sehen uns doch jeden Tag im Wohnheim.[n][uf 1 1][e]

[msg MSG_056_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 3 0 65535 1142 0 0]Typisch Dummpei, immer ein schlechter Einfluss. Er kann so kindisch sein ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0]Ich finde jedenfalls, dass Tage wie dieser wirklich schön sein können.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0]Bleiben wir einfach optimistisch und hoffen auf das Beste.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Yukari Takeba]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

