[msg MSG_000_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hallo [uf 4 1]-chan. Bist du auch gerade auf Patrouille?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]War nur ein Witz. Ich möchte diesen Ausflug genießen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Hoffentlich gibt es keinen Ärger, solange ...[n][uf 1 1][e]

[msg MSG_001_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Hey, Odagiri-kun! Hast du diese Snacks schon probiert?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Die sind richtig lecker![n][uf 1 1][e]

[msg MSG_002_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Nein, hab ich noch nicht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Es sind keine mehr übrig.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Sollte sich nicht jeder nur einen nehmen?[n][uf 1 1][e]

[msg MSG_003_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Oh, echt? Ups ... Ich hab alle aufgegessen. Sorry![n][uf 1 1][e]

[msg MSG_004_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Das dachte ich mir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Ich tu einfach so, als hätte es gar keine gegeben.[n][uf 1 1][e]

[msg MSG_005_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Sorry, Odagiri-kun. Ich sehe nachher im Souvenirshop nach, ob es noch mehr Snacks gibt.[n][uf 1 1][e]

[msg MSG_006_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 13 0 0]N-Nicht nötig. Ich will eh nichts probieren ...[n][uf 1 1][e]

[msg MSG_007_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hallo [uf 4 1]-chan. Bist du auch gerade auf Patrouille?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]War nur ein Witz. Ich möchte diesen Ausflug genießen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Hoffentlich gibt es keinen Ärger, solange ...[n][uf 1 1][e]

[msg MSG_008_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Hey, Odagiri-kun! Hast du diese Snacks schon probiert?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Die sind richtig lecker![n][uf 1 1][e]

[msg MSG_009_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Nein, hab ich noch nicht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Es sind keine mehr übrig.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Sollte sich nicht jeder nur einen nehmen?[n][uf 1 1][e]

[msg MSG_010_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Oh, echt? Oje ... Ich hab alle aufgegessen. Sorry![n][uf 1 1][e]

[msg MSG_011_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Das dachte ich mir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Ich tu einfach so, als hätte es gar keine gegeben.[n][uf 1 1][e]

[msg MSG_012_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Sorry, Odagiri-kun. Ich sehe nachher im Souvenirshop nach, ob es noch mehr Snacks gibt.[n][uf 1 1][e]

[msg MSG_013_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 13 0 0]N-Nicht nötig. Ich will eh nichts probieren ...[n][uf 1 1][e]

[msg MSG_014_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 1 0 0][uf 4 1]-chan, du bist auch hier? Stimmt, du bist ja im zweiten Jahr.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Hast du diese Snacks eigentlich schon probiert?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Die sind richtig lecker![n][uf 1 1][e]

[msg MSG_015_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Nein, ich bin noch nicht dazu gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Weißt du, warum dieses Tablett leer? Sollte nicht jeder nur einen nehmen?[n][uf 1 1][e]

[msg MSG_016_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Oh, echt? Oje ... Ich hab alle aufgegessen. Sorry![n][uf 1 1][e]

[msg MSG_017_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Das dachte ich mir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Ich tu einfach so, als hätte es gar keine gegeben.[n][uf 1 1][e]

[msg MSG_018_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Sorry, Odagiri-kun. Ich sehe nachher im Souvenirshop nach, ob es noch mehr Snacks gibt.[n][uf 1 1][e]

[msg MSG_019_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 10 0 0]N-Nicht nötig. Ich will eh nichts probieren ...[n][uf 1 1][e]

[msg MSG_020_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Als Mitglied des Disziplinarkomitees muss ich selbst auf so einem Ausflug auf alles achten.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Hoffentlich gibt es keinen Ärger, solange ...[n][uf 1 1][e]

[msg MSG_021_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Hey, Odagiri-kun! Hast du diese Snacks schon probiert?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Die sind richtig lecker![n][uf 1 1][e]

[msg MSG_022_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Nein, hab ich noch nicht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Es sind keine mehr übrig.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Sollte sich nicht jeder nur einen nehmen?[n][uf 1 1][e]

[msg MSG_023_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Oh, echt? Oje ... Ich hab alle aufgegessen. Sorry![n][uf 1 1][e]

[msg MSG_024_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Das dachte ich mir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Ich tu einfach so, als hätte es gar keine gegeben.[n][uf 1 1][e]

[msg MSG_025_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Sorry, Odagiri-kun. Ich sehe nachher im Souvenirshop nach, ob es noch mehr Snacks gibt.[n][uf 1 1][e]

[msg MSG_026_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 1][uf 3 1 1 0 4 12 0 0]N-Nicht nötig. Ich will eh nichts probieren ...[n][uf 1 1][e]

[msg MSG_027_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Oh, hey, [uf 4 1]-chan. Der Ausflug heute war echt anstrengend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Ich hatte mich darauf gefreut, all die historischen Orte zu besuchen, aber ...[n][uf 1 1][e]

[msg MSG_028_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Es war alles einfach etwas zu viel auf einmal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Von den älteren Touristen in unserer Gruppe sind sogar manche umgekippt.[n][uf 1 1][e]

[msg MSG_029_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Zum Glück warst du da, Keisuke. Dank dir ist es nicht ganz so schlimm gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Trotzdem war das ziemlich schockierend.[n][uf 1 1][e]

[msg MSG_030_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Sogar der Touristenführer ist in Ohnmacht gefallen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Wie du die Situation gerettet hast, war echt beeindruckend, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Hast du je daran gedacht, Polizist zu werden?[n][uf 1 1][e]

[msg MSG_031_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Wie ...? Äh, auf die Idee war ich bisher nicht gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Baden wir in den heißen Quellen. Nach all dem Stress bin ich total verschwitzt.[n][uf 1 1][e]

[msg MSG_032_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Du hättest dich nicht einmischen müssen, aber ich schätze, du kannst einfach nicht anders, Keisuke.[n][uf 1 1][e]

[msg MSG_033_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Haha, dito. Du warst doch der Erste, der aktiv geworden ist.[n][uf 1 1][e]

[msg MSG_034_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Oh, hey, [uf 4 1]-chan. Der Ausflug heute war echt anstrengend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Ich hatte mich darauf gefreut, all die historischen Orte zu besuchen, aber ...[n][uf 1 1][e]

[msg MSG_035_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Es war alles einfach etwas zu viel auf einmal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Von den älteren Touristen in unserer Gruppe sind sogar manche umgekippt.[n][uf 1 1][e]

[msg MSG_036_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Zum Glück warst du da, Keisuke. Dank dir ist es nicht ganz so schlimm gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Trotzdem war das ziemlich schockierend.[n][uf 1 1][e]

[msg MSG_037_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Sogar der Touristenführer ist in Ohnmacht gefallen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Wie du die Situation gerettet hast, war echt beeindruckend, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Hast du je daran gedacht, Polizist zu werden?[n][uf 1 1][e]

[msg MSG_038_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Wie ...? Äh, auf die Idee war ich bisher nicht gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Baden wir in den heißen Quellen. Nach all dem Stress bin ich total verschwitzt.[n][uf 1 1][e]

[msg MSG_039_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Du hättest dich nicht einmischen müssen, aber ich schätze, du kannst einfach nicht anders, Keisuke.[n][uf 1 1][e]

[msg MSG_040_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Ha, dito. Du warst doch der Erste, der aktiv geworden ist.[n][uf 1 1][e]

[msg MSG_041_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hi, [uf 4 1]-chan. Wie war euer Ausflug heute?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Bei uns gab's ganz schön Probleme. Ich wollte die Schreine sehen, aber ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Von den älteren Touristen in unserer Gruppe sind sogar manche umgekippt.[n][uf 1 1][e]

[msg MSG_042_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Zum Glück warst du da, Keisuke. Dank dir ist es nicht ganz so schlimm gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Trotzdem war das ziemlich schockierend.[n][uf 1 1][e]

[msg MSG_043_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Sogar der Touristenführer ist in Ohnmacht gefallen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Wie du die Situation gerettet hast, war echt beeindruckend, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Hast du je daran gedacht, Polizist zu werden?[n][uf 1 1][e]

[msg MSG_044_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Wie ...? Äh, auf die Idee war ich bisher nicht gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Baden wir in den heißen Quellen. Nach all dem Stress bin ich total verschwitzt.[n][uf 1 1][e]

[msg MSG_045_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Du hättest dich nicht einmischen müssen, aber ich schätze, du kannst einfach nicht anders, Keisuke.[n][uf 1 1][e]

[msg MSG_046_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Haha, dito. Du warst doch der Erste, der aktiv geworden ist.[n][uf 1 1][e]

[msg MSG_048_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Es war alles einfach etwas zu viel auf einmal.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Von den älteren Touristen in unserer Gruppe sind sogar manche umgekippt.[n][uf 1 1][e]

[msg MSG_047_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Es war ein langer Tag. Ich hatte mich darauf gefreut, all die historischen Orte zu besuchen, aber ...[n][uf 1 1][e]

[msg MSG_049_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Zum Glück warst du da, Keisuke. Dank dir ist es nicht ganz so schlimm gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Trotzdem war das ziemlich schockierend.[n][uf 1 1][e]

[msg MSG_050_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Sogar der Touristenführer ist in Ohnmacht gefallen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Wie du die Situation gerettet hast, war echt beeindruckend, Odagiri-kun.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Hast du je daran gedacht, Polizist zu werden?[n][uf 1 1][e]

[msg MSG_051_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Wie ...? Äh, auf die Idee war ich bisher nicht gekommen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Baden wir in den heißen Quellen. Nach all dem Stress bin ich total verschwitzt.[n][uf 1 1][e]

[msg MSG_052_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Du hättest dich nicht einmischen müssen, aber ich schätze, du kannst einfach nicht anders, Keisuke.[n][uf 1 1][e]

[msg MSG_053_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Haha, dito. Du warst doch der Erste, der aktiv geworden ist.[n][uf 1 1][e]

[msg MSG_054_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hey, [uf 4 1]-chan. Sieht meine Hose in Ordnung aus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Es war vielleicht alles etwas viel.[n][uf 1 1][e]

[msg MSG_055_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Am Kamogawa ist es schön, oder?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Odagiri-kun wollte Steine hüpfen lassen, doch dann ist er ausgerutscht und ...[n][uf 1 1][e]

[msg MSG_056_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Können wir das bitte lassen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Außerdem war das deine Schuld, Keisuke. Du meintest, ich würde es nicht zum anderen Ufer schaffen.[n][uf 1 1][e]

[msg MSG_057_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Warst du denn nicht neugierig? Die Windverhältnisse waren perfekt.[n][uf 1 1][e]

[msg MSG_058_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Warum sollte man so was überhaupt machen?[n][uf 1 1][e]

[msg MSG_059_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Weil ich es ... lustig finde?[n][uf 1 1][e]

[msg MSG_060_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Ich wollte wissen, was es bringt. Es war total sinnlos.[n][uf 1 1][e]

[msg MSG_061_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Weißt du nicht mehr? In der Grundschulzeit haben wir ständig Steine hüpfen lassen.[n][uf 1 1][e]

[msg MSG_062_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Ja, aber jetzt sind wir in der Highschool. Du bist im letzten Jahr.[n][uf 1 1][e]

[msg MSG_063_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Du hast so entschlossen gewirkt, bis du ausgerutscht und hingefallen bist.[n][uf 1 1][e]

[msg MSG_064_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]Wie gesagt, könnten wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_065_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, du machst mir so Angst, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_066_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]Dass meine letzte Erinnerung an diesen Ausflug so peinlich sein würde ...[n][uf 1 1][e]

[msg MSG_067_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]Ist doch keine große Sache. Das andere Ufer war einfach etwas zu weit entfernt.[n][uf 1 1][e]

[msg MSG_068_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Hey, [uf 4 1]-chan. Sieht meine Hose in Ordnung aus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Es war vielleicht alles etwas viel.[n][uf 1 1][e]

[msg MSG_069_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Am Kamogawa ist es schön, oder?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Odagiri-kun wollte Steine hüpfen lassen, doch dann ist er ausgerutscht und ...[n][uf 1 1][e]

[msg MSG_070_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Können wir das bitte lassen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Außerdem war das deine Schuld, Keisuke. Du meintest, ich würde es nicht zum anderen Ufer schaffen.[n][uf 1 1][e]

[msg MSG_071_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Warst du denn nicht neugierig? Die Windverhältnisse waren perfekt.[n][uf 1 1][e]

[msg MSG_072_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Warum sollte man so was überhaupt machen?[n][uf 1 1][e]

[msg MSG_073_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Weil ich es ... lustig finde?[n][uf 1 1][e]

[msg MSG_074_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Ich wollte wissen, was es bringt. Es war total sinnlos.[n][uf 1 1][e]

[msg MSG_075_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Weißt du nicht mehr? In der Grundschulzeit haben wir ständig Steine hüpfen lassen.[n][uf 1 1][e]

[msg MSG_076_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Ja, aber jetzt sind wir in der Highschool. Du bist im letzten Jahr.[n][uf 1 1][e]

[msg MSG_077_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Du hast so entschlossen gewirkt, bis du ausgerutscht und hingefallen bist.[n][uf 1 1][e]

[msg MSG_078_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]Wie gesagt, könnten wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_079_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, du machst mir so Angst, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_080_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]Dass meine letzte Erinnerung an diesen Ausflug so peinlich sein würde ...[n][uf 1 1][e]

[msg MSG_081_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]Ist doch keine große Sache. Das andere Ufer war einfach etwas zu weit entfernt.[n][uf 1 1][e]

[msg MSG_082_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Du da. Sieht meine Hose in Ordnung aus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Es war vielleicht alles etwas viel.[n][uf 1 1][e]

[msg MSG_083_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Am Kamogawa ist es schön, oder?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Odagiri-kun wollte Steine hüpfen lassen, doch dann ist er ausgerutscht und ...[n][uf 1 1][e]

[msg MSG_084_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Können wir das bitte lassen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Außerdem war das deine Schuld, Keisuke. Du meintest, ich würde es nicht zum anderen Ufer schaffen.[n][uf 1 1][e]

[msg MSG_085_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Warst du denn nicht neugierig? Die Windverhältnisse waren perfekt.[n][uf 1 1][e]

[msg MSG_086_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Warum sollte man so was überhaupt machen?[n][uf 1 1][e]

[msg MSG_087_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Weil ich es ... lustig finde?[n][uf 1 1][e]

[msg MSG_088_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Ich wollte wissen, was es bringt. Es war total sinnlos.[n][uf 1 1][e]

[msg MSG_089_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Weißt du nicht mehr? In der Grundschulzeit haben wir ständig Steine hüpfen lassen.[n][uf 1 1][e]

[msg MSG_090_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Ja, aber jetzt sind wir in der Highschool. Du bist im letzten Jahr.[n][uf 1 1][e]

[msg MSG_091_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Du hast so entschlossen gewirkt, bis du ausgerutscht und hingefallen bist.[n][uf 1 1][e]

[msg MSG_092_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]Wie gesagt, könnten wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_093_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, du machst mir so Angst, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_094_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]Dass meine letzte Erinnerung an diesen Ausflug so peinlich sein würde ...[n][uf 1 1][e]

[msg MSG_095_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]Ist doch keine große Sache. Das andere Ufer war einfach etwas zu weit entfernt.[n][uf 1 1][e]

[msg MSG_096_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 1 0 0]Du da. Sieht meine Hose in Ordnung aus?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 2 0 0]Es war vielleicht alles etwas viel.[n][uf 1 1][e]

[msg MSG_097_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 3 0 0]Am Kamogawa ist es schön, oder?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 4 0 0]Odagiri-kun wollte Steine hüpfen lassen, doch dann ist er ausgerutscht und ...[n][uf 1 1][e]

[msg MSG_098_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 5 0 0]Können wir das bitte lassen?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 6 0 0]Außerdem war das deine Schuld, Keisuke. Du meintest, ich würde es nicht zum anderen Ufer schaffen.[n][uf 1 1][e]

[msg MSG_099_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 7 0 0]Warst du denn nicht neugierig? Die Windverhältnisse waren perfekt.[n][uf 1 1][e]

[msg MSG_100_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0][uf 3 1 1 0 4 8 0 0]Warum sollte man so was überhaupt machen?[n][uf 1 1][e]

[msg MSG_101_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 9 0 0]Weil ich es ... lustig finde?[n][uf 1 1][e]

[msg MSG_102_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 10 0 0]Ich wollte wissen, was es bringt. Es war total sinnlos.[n][uf 1 1][e]

[msg MSG_103_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 11 0 0]Weißt du nicht mehr? In der Grundschulzeit haben wir ständig Steine hüpfen lassen.[n][uf 1 1][e]

[msg MSG_104_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 12 0 0]Ja, aber jetzt sind wir in der Highschool. Du bist im letzten Jahr.[n][uf 1 1][e]

[msg MSG_105_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 13 0 0]Du hast so entschlossen gewirkt, bis du ausgerutscht und hingefallen bist.[n][uf 1 1][e]

[msg MSG_106_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 2 65535 65535 0 0][uf 3 1 1 0 4 14 0 0]Wie gesagt, könnten wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_107_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 1 65535 65535 0 0][uf 3 1 1 0 4 15 0 0]Oooh, du machst mir so Angst, Odagiri-kun.[n][uf 1 1][e]

[msg MSG_108_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 3 65535 65535 0 0][uf 3 1 1 0 4 16 0 0]Dass meine letzte Erinnerung an diesen Ausflug so peinlich sein würde ...[n][uf 1 1][e]

[msg MSG_109_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0][uf 3 1 1 0 4 17 0 0]Ist doch keine große Sache. Das andere Ufer war einfach etwas zu weit entfernt.[n][uf 1 1][e]

[msg MSG_110_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Hey, ist meine Hose schmutzig?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Ein Hirsch hat mir das Futter aus der Tasche gefressen ...[n][uf 1 1][e]

[msg MSG_111_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich wusste gar nicht, dass es in[n]Kyoto Hirsche gibt. Aber weißt du,[n]was Odagiri-kun mit dem Futter vorhatte?[n][uf 1 1][e]

[msg MSG_112_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Können wir bitte nicht darüber reden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Wenn du nicht gesagt hättest, dass du auf einem Hirsch reiten willst ...[n][uf 1 1][e]

[msg MSG_113_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Wolltest du etwa nicht auf einem reiten? Das Geweih wäre doch der perfekte Lenker ...[n][uf 1 1][e]

[msg MSG_114_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Und wozu soll das gut sein?[n][uf 1 1][e]

[msg MSG_115_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Keine Ahnung ... Es ist cool?[n][uf 1 1][e]

[msg MSG_116_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Nein, ist es nicht.[n][uf 1 1][e]

[msg MSG_117_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]In der Grundschule haben wir doch andauernd verrückte Sachen gemacht![n][uf 1 1][e]

[msg MSG_118_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Ja ... und jetzt sind wir in der Highschool.[n]Du bist im dritten Jahr.[n][uf 1 1][e]

[msg MSG_119_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Aber ... das Hirschfutter ...[n][uf 1 1][e]

[msg MSG_120_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Können wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_121_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich habe echt Angst vor dir, Odagiri-kun ...[n][uf 1 1][e]

[msg MSG_122_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Hey, ist meine Hose schmutzig?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Ein Hirsch hat mir das Futter aus der Tasche gefressen ...[n][uf 1 1][e]

[msg MSG_123_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Ich wusste gar nicht, dass es in Kyoto Hirsche gibt. Weißt du, Odagiri-kun, dass Tiercracker ...[n][uf 1 1][e]

[msg MSG_124_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Können wir bitte nicht darüber reden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Wenn du nicht gesagt hättest, dass du auf einem Hirsch reiten willst ...[n][uf 1 1][e]

[msg MSG_125_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Wolltest du etwa nicht auf einem reiten? Das Geweih wäre doch der perfekte Lenker ...[n][uf 1 1][e]

[msg MSG_126_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Und wozu soll das gut sein?[n][uf 1 1][e]

[msg MSG_127_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Keine Ahnung ... Es ist cool?[n][uf 1 1][e]

[msg MSG_128_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Nein, ist es nicht.[n][uf 1 1][e]

[msg MSG_129_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]In der Grundschule haben wir doch andauernd verrückte Sachen gemacht![n][uf 1 1][e]

[msg MSG_130_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Ja ... und jetzt sind wir in der Highschool.[n]Du bist im dritten Jahr.[n][uf 1 1][e]

[msg MSG_131_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Aber ... das Hirschfutter ...[n][uf 1 1][e]

[msg MSG_132_0_0 [Hidetoshi Odagiri]]
[uf 0 5 65278][uf 2 1][uf 4 5 102 0 65535 65535 0 0]Können wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_133_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Ich habe echt Angst vor dir, Odagiri-kun ...[n][uf 1 1][e]

[msg MSG_134_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Hey, ist meine Hose schmutzig?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ein Hirsch hat mir das Futter aus der Tasche gefressen ...[n][uf 1 1][e]

[msg MSG_135_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich wusste gar nicht, dass es in Kyoto Hirsche gibt. Weißt du, Odagiri-kun, dass Tiercracker ...[n][uf 1 1][e]

[msg MSG_136_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Können wir bitte nicht darüber reden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Wenn du nicht gesagt hättest, dass du auf einem Hirsch reiten willst ...[n][uf 1 1][e]

[msg MSG_137_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Wolltest du etwa nicht auf einem reiten? Das Geweih wäre doch der perfekte Lenker ...[n][uf 1 1][e]

[msg MSG_138_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Und wozu soll das gut sein?[n][uf 1 1][e]

[msg MSG_139_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Keine Ahnung ... Es ist cool?[n][uf 1 1][e]

[msg MSG_140_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Nein, ist es nicht.[n][uf 1 1][e]

[msg MSG_141_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]In der Grundschule haben wir doch andauernd verrückte Sachen gemacht![n][uf 1 1][e]

[msg MSG_142_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Ja ... und jetzt sind wir in der Highschool.[n]Du bist im dritten Jahr.[n][uf 1 1][e]

[msg MSG_143_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Aber ... das Hirschfutter ...[n][uf 1 1][e]

[msg MSG_144_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Können wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_145_0_0 [Keisuke Hiraga]]
[uf 0 5 65278][uf 2 1][uf 4 5 108 0 65535 65535 0 0]Ich habe echt Angst vor dir, Odagiri-kun ...[n][uf 1 1][e]

[msg MSG_146_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Hey, ist meine Hose schmutzig?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Ein Hirsch hat mir das Futter aus der Tasche gefressen ...[n][uf 1 1][e]

[msg MSG_147_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Ich wusste gar nicht, dass es in Kyoto Hirsche gibt. Weißt du, Odagiri-kun, dass Tiercracker ...[n][uf 1 1][e]

[msg MSG_148_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Können wir bitte nicht darüber reden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Wenn du nicht gesagt hättest, dass du auf einem Hirsch reiten willst ...[n][uf 1 1][e]

[msg MSG_149_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Wolltest du etwa nicht auf einem reiten? Das Geweih wäre doch der perfekte Lenker ...[n][uf 1 1][e]

[msg MSG_150_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Und wozu soll das gut sein?[n][uf 1 1][e]

[msg MSG_151_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Keine Ahnung ... Es ist cool?[n][uf 1 1][e]

[msg MSG_152_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Nein, ist es nicht.[n][uf 1 1][e]

[msg MSG_153_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]In der Grundschule haben wir doch andauernd verrückte Sachen gemacht![n][uf 1 1][e]

[msg MSG_154_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Ja ... und jetzt sind wir in der Highschool.[n]Du bist im dritten Jahr.[n][uf 1 1][e]

[msg MSG_155_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Aber ... das Hirschfutter ...[n][uf 1 1][e]

[msg MSG_156_0_0 [Strenger Schüler]]
[uf 0 5 65278][uf 2 1]Können wir bitte das Thema wechseln?[n][uf 1 1][e]

[msg MSG_157_0_0 [Freundlicher Schüler]]
[uf 0 5 65278][uf 2 1]Ich habe echt Angst vor dir, Odagiri-kun ...[n][uf 1 1][e]

