[msg MSG_000_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 3 102 65535 0 0][uf 3 1 1 0 4 1 0 0][uf 4 1]-chan! Bitte hilf uns![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 4 102 65535 0 0][uf 3 1 1 0 4 2 0 0]Junpei-chan will nicht aufhören ... Ah! Ahhh![n][uf 1 1][e]

[msg MSG_001_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 4 3 0 0]Hehe, allez hopp! Nimm das! Und das![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 102 65535 0 0][uf 3 1 1 0 4 4 0 0]Komm schon, am Strand muss man im Wasser kämpfen! Ist das nicht cool?[n][uf 1 1][e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 102 65535 0 0][uf 3 1 1 0 4 5 0 0]Hey, hör auf! Du gehst zu weit! Na schön! Du wolltest es nicht anders![n][uf 1 1][e]

[msg MSG_003_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 155 65535 0 0][uf 3 1 1 0 4 1 0 0]Vorhin habe ich Yukari-chan und Kirijo-senpai zusammen gesehen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 6 0 155 65535 0 0][uf 3 1 1 0 4 2 0 0]Sie lachten, während sie sich unterhielten. Das sieht man nicht oft.[n][uf 1 1][e]

[msg MSG_004_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 155 65535 0 0][uf 3 1 1 0 4 1 0 0]Zum Glück geht es Kirijo-senpai besser.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

