[msg MSG_000_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12050 0 0]Könnte ich doch nur jemanden finden, der die Herzen unserer Kunden stehlen könnte ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Es muss doch ein gut aussehendes junges Mädchen geben, der die Hausmänner ganz wild macht ...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Gleich hier.[e]
[uf 0 5 65278][uf 2 1]Irgendwo da draußen.[e]

[msg MSG_002_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0][uf 4 25 113]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0]Wo? Ich sehe niemanden. Meine Güte, verschwende nicht meine Zeit![n][uf 1 1][e]

[msg MND_003_0_0]
[uf 0 5 65278][uf 2 1]Das muss der Typ sein,[n]den Maya im Fernsehen gesehen hat.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Er scheint aber kein Interesse an mir zu haben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Hätte ich genug [uf 4 30 1 1 1 0], um [uf 4 31 1 4 1 0] zu sein, könnte ich seine Aufmerksamkeit erregen.[n][uf 1 1][e]

[msg MSG_004_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 3 0 65535 12069 0 0]Natürlich, du Schwachkopf! Ich muss ihn bloß finden![n][uf 1 1][e]

[msg MSG_005_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12008 0 0]Bist du aber hübsch.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Könnte ich dich für eine Werbeaktion interessieren? Oh, du gehst noch zur Schule?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Hmm ... aber vielleicht könnte ich sie ausbilden ...[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Der Mann murmelt vor sich hin ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Mein [uf 4 30 1 1 1 0] hat seine Aufmerksamkeit erweckt.[n][uf 1 1][e]

[msg MSG_007_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12004 0 0]Junge Dame, hast du Träume, die in Erfüllung gehen sollen? Ich habe eine einmalige Gelegenheit für dich ...[n][uf 1 1][e]

[sel SEL_008_0_0 top]
[uf 0 5 65278][uf 2 1]Erzähl mir mehr.[e]
[uf 0 5 65278][uf 2 1]Kein Interesse.[e]

[msg MSG_009_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12017 0 0]Oh, wirklich? Du lässt dir die Chance entgehen, unvorstellbar reich zu werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Tja, wenn du meinst ...[n][uf 1 1][e]

[msg MSG_010_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12061 0 0]Das hier bleibt unter uns, erzähl es nicht weiter, okay?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Ich kann dich reich machen – garantiert.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Du brauchst nur 20.000 Yen und deine Investition verzehnfacht, nein, verhundertfacht sich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Und das Beste ist: Du musst nichts dafür tun! Du wirst buchstäblich im Schlaf unverschämt reich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Gib mir einfach die 20.000 Yen, ich erledige den Rest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Und, was sagst du?[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]Okay.[e]
[uf 0 5 65278][uf 2 1]Kein Interesse.[e]

[msg MND_012_0_0]
[uf 0 5 65278][uf 2 1]Ich habe nicht genug Geld.[n][uf 1 1][e]

[msg MSG_013_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Was? So viel hast du nicht? Tja, dann ist das Angebot leider vom Tisch.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]Ich gab dem Mann 20.000 Yen.[n][uf 1 1][e]

[msg MSG_015_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12018 0 0]Das genügt. Ich melde mich, wenn du reich bist.[n][uf 1 1][e]

[msg MSG_016_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Oh, wirklich? Du lässt dir die Chance entgehen, unvorstellbar reich zu werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Tja, wenn du meinst ...[n][uf 1 1][e]

[msg MSG_017_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12008 0 0]Hast du über mein Angebot nachgedacht?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Du kannst ein Vermögen verdienen, indem du nur 20.000 Yen investierst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Du musst mir einfach nur das Geld geben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Und, was sagst du?[n][uf 1 1][e]

[sel SEL_018_0_0 top]
[uf 0 5 65278][uf 2 1]Okay.[e]
[uf 0 5 65278][uf 2 1]Kein Interesse.[e]

[msg MND_019_0_0]
[uf 0 5 65278][uf 2 1]Ich habe nicht genug Geld.[n][uf 1 1][e]

[msg MSG_020_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Was? So viel hast du nicht? Tja, dann ist das Angebot leider vom Tisch.[n][uf 1 1][e]

[msg MND_021_0_0]
[uf 0 5 65278][uf 2 1]Ich gab dem Mann 20.000 Yen.[n][uf 1 1][e]

[msg MSG_022_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12018 0 0]Das genügt. Ich melde mich, wenn du reich bist.[n][uf 1 1][e]

[msg MSG_023_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Oh, wirklich? Du lässt dir die Chance entgehen, unvorstellbar reich zu werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Tja, wenn du meinst ...[n][uf 1 1][e]

[msg MSG_024_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12015 0 0]Ich melde mich, wenn du reich bist.[n][uf 1 1][e]

[msg MSG_025_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12004 0 0]Oh, da bist du ja ... ich habe nach dir gesucht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Ich habe schlechte Neuigkeiten, was deine Investition angeht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Es läuft nicht so gut wie geplant. Wir können immer noch Profit machen, aber ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Ich brauche noch einmal 10.000 Yen, um alles wieder auf Kurs zu bringen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Bist du bereit, noch einmal so viel nachzuschießen?[n][uf 1 1][e]

[sel SEL_026_0_0 top]
[uf 0 5 65278][uf 2 1]Klar.[e]
[uf 0 5 65278][uf 2 1]Vergiss es.[e]

[msg MND_027_0_0]
[uf 0 5 65278][uf 2 1]Ich habe nicht genug Geld.[n][uf 1 1][e]

[msg MSG_028_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Was? So viel hast du nicht? Tja, dann ist das Angebot leider vom Tisch.[n][uf 1 1][e]

[msg MND_029_0_0]
[uf 0 5 65278][uf 2 1]Ich gab dem Mann 10.000 Yen.[n][uf 1 1][e]

[msg MSG_030_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Ausgezeichnet. Ich melde mich, wenn du reich bist.[n][uf 1 1][e]

[msg MSG_031_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Oh, wirklich? Du lässt dir die Chance entgehen, unvorstellbar reich zu werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Tja, wenn du meinst ...[n][uf 1 1][e]

[msg MSG_032_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12001 0 0]Hast du über mein Angebot nachgedacht?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Du kannst ein Vermögen verdienen, indem du 10.000 Yen mehr investierst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Du musst mir nur das Geld geben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Keine Frage, oder? Das machst du.[n][uf 1 1][e]

[sel SEL_033_0_0 top]
[uf 0 5 65278][uf 2 1]Klar.[e]
[uf 0 5 65278][uf 2 1]Vergiss es.[e]

[msg MND_034_0_0]
[uf 0 5 65278][uf 2 1]Ich habe nicht genug Geld.[n][uf 1 1][e]

[msg MSG_035_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Was? So viel hast du nicht? Tja, dann ist das Angebot leider vom Tisch.[n][uf 1 1][e]

[msg MND_036_0_0]
[uf 0 5 65278][uf 2 1]Ich gab dem Mann 10.000 Yen.[n][uf 1 1][e]

[msg MSG_037_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12018 0 0]Ausgezeichnet. Ich melde mich, wenn du reich bist.[n][uf 1 1][e]

[msg MSG_038_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Oh, wirklich? Du lässt dir die Chance entgehen, unvorstellbar reich zu werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Tja, wenn du meinst ...[n][uf 1 1][e]

[msg MSG_039_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12035 0 0]Keine Sorge. Ich melde mich, wenn du reich bist.[n][uf 1 1][e]

[msg MSG_040_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12004 0 0]Ach, da bist du ja ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0]Es gibt wieder ein kleines Problem. Ein paar andere Investoren sind ausgestiegen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Doch da es nun weniger sind, machen alle mehr Profit! Würdest du also noch mehr investieren?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Noch mal 10.000 Yen würden locker reichen![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12067 0 0]Bist du dabei?[n][uf 1 1][e]

[sel SEL_041_0_0 top]
[uf 0 5 65278][uf 2 1]Klar.[e]
[uf 0 5 65278][uf 2 1]Vergiss es.[e]

[msg MND_042_0_0]
[uf 0 5 65278][uf 2 1]Ich habe nicht genug Geld.[n][uf 1 1][e]

[msg MSG_043_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Was? So viel hast du nicht? Tja, dann ist das Angebot leider vom Tisch.[n][uf 1 1][e]

[msg MND_044_0_0]
[uf 0 5 65278][uf 2 1]Ich gab dem Mann 10.000 Yen.[n][uf 1 1][e]

[msg MSG_045_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Oh, wirklich? Du lässt dir die Chance entgehen, unvorstellbar reich zu werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Tja, wenn du meinst ...[n][uf 1 1][e]

[msg MSG_046_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12004 0 0]Hast du über mein Angebot nachgedacht?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Ich brauche bloß noch mal 10.000 Yen von dir.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12067 0 0]Das machst du, oder?![n][uf 1 1][e]

[sel SEL_047_0_0 top]
[uf 0 5 65278][uf 2 1]Klar.[e]
[uf 0 5 65278][uf 2 1]Vergiss es.[e]

[msg MND_048_0_0]
[uf 0 5 65278][uf 2 1]Ich habe nicht genug Geld.[n][uf 1 1][e]

[msg MSG_049_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Was? So viel hast du nicht? Tja, dann ist das Angebot leider vom Tisch.[n][uf 1 1][e]

[msg MND_050_0_0]
[uf 0 5 65278][uf 2 1]Ich gab dem Mann 10.000 Yen.[n][uf 1 1][e]

[msg MSG_051_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Oh, wirklich? Du lässt dir die Chance entgehen, unvorstellbar reich zu werden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Tja, wenn du meinst ...[n][uf 1 1][e]

[msg MSG_052_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 0 0 0 0 0 0][uf 4 25 113]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Mein dummer kleiner Lehrling ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 3 0 65535 12070 0 0]Hast du noch nicht gemerkt, dass du reingelegt wirst? Alles, was ich gesagt habe, war höchst verdächtig![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0]*seufz*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0]Dummheit müsste verboten werden.[n][uf 1 1][e]

[msg MSG_053_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12052 0 0]Klar, du hast auch ein paar gute Eigenschaften, aber wenn du so naiv bleibst, nutzen dich alle nur aus.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Bleib an meiner Seite, dann zeige ich dir, wie man im Leben gewinnt.[n][uf 1 1][e]

[msg MND_054_0_0]
[uf 0 5 65278][uf 2 1]Dieser Mann scheint es ernst zu meinen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Soll ich ihm für einige Zeit zuhören?[n][uf 1 1][e]

[sel SEL_055_0_0 top]
[uf 0 5 65278][uf 2 1]Ja, bitte.[e]
[uf 0 5 65278][uf 2 1]Nein danke.[e]

[msg MSG_056_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 3 0 65535 12069 0 0]Oje! Du willst so eine einmalige Gelegenheit vergeuden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0]So eine Schande. Dummheit ist wirklich ein Verbrechen.[n][uf 1 1][e]

[msg MSG_057_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12077 0 0]Soll ich dir noch mehr Geld aus der Tasche ziehen. Du solltest endlich mal nachdenken.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Halt dich an mich. Mein Rat ist gut und gern 40.000 Yen wert.[n][uf 1 1][e]

[msg MND_058_0_0]
[uf 0 5 65278][uf 2 1]Dieser Mann scheint es ernst zu meinen.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Soll ich ihm für einige Zeit zuhören?[n][uf 1 1][e]

[sel SEL_059_0_0 top]
[uf 0 5 65278][uf 2 1]Ja, bitte.[e]
[uf 0 5 65278][uf 2 1]Nein danke.[e]

[msg MSG_060_0_0 [Mann im Anzug]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 2 65535 65535 0 0][uf 3 1 3 0 65535 12069 0 0]Oje! Du willst so eine einmalige Gelegenheit vergeuden?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0]So eine Schande. Dummheit ist wirklich ein Verbrechen.[n][uf 1 1][e]

[msg MSG_061_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Oh, wenn das nicht [uf 4 1] ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12007 0 0]Hast du gerade Zeit? Falls ja, kann ich dir eine wertvolle Lektion fürs Leben beibringen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Kostenlos, versteht sich.[n][uf 1 1][e]

[msg MND_062_0_0]
[uf 0 5 65278][uf 2 1]Präsident Tanaka will anscheinend mit mir reden.[n][uf 1 1][e]

[msg MND_063_0_0]
[uf 0 5 65278][uf 2 1]Soll ich etwas Zeit mit ihm verbringen?[n][uf 1 1][e]

[sel SEL_064_0_0 top]
[uf 0 5 65278][uf 2 1]Mit ihm sprechen[e]
[uf 0 5 65278][uf 2 1]Social-Link-Status anzeigen[e]
[uf 0 5 65278][uf 2 1]Jetzt nicht[e]

[msg MSG_065_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12067 0 0]Bist du aber begeistert.[n][uf 1 1][e]

[msg MSG_066_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]Hmm ... Es ist nicht so, dass die Armen keine Chance haben, sie ergreifen bloß nicht die Gelegenheit.[n][uf 1 1][e]

[msg MSG_067_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12009 0 0]Oh, wenn das nicht [uf 4 1] ist. Beschäftigt dich etwas?[n][uf 1 1][e]

[sel SEL_068_0_0 top]
[uf 0 5 65278][uf 2 1]Gib mir dein Autogramm![e]
[uf 0 5 65278][uf 2 1]Darf ich dein Autogramm haben?[e]

[msg MSG_069_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12051 0 0]Hm? Mein Autogramm? Na ja, normalerweise verlange ich für so was eine schöne Stange Geld ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Aber dieses eine Mal gebe ich sie dir kostenlos. Im Gegenzug verbreitest du, wie großzügig ich bin![n][uf 1 1][e]

[msg MSG_070_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Rahm es dir ein, das wird mal ein wertvolles Familienerbstück.[n][uf 1 1][e]

[msg MND_071_0_0]
[uf 0 5 65278][uf 2 1]Ich habe das Autogramm einer Berühmtheit.[n]Ich sollte es Elizabeth zeigen ...[n][uf 1 1][e]

[msg MSG_072_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12008 0 0]Oh, wenn das nicht [uf 4 1] ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Hast du gerade Zeit? Falls ja, kann ich dir eine wertvolle Lektion fürs Leben beibringen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Kostenlos, versteht sich.[n][uf 1 1][e]

[msg MSG_073_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Bist du aber begeistert. Dann lass uns keine Zeit vergeuden.[n][uf 1 1][e]

[msg MSG_074_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12008 0 0]Oh, wenn das nicht [uf 4 1] ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Hast du etwas Zeit für mich? Dann erteile ich dir noch eine Lebenslektion.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Kostenlos, versteht sich.[n][uf 1 1][e]

[msg MSG_075_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12067 0 0]Mir gefällt deine Haltung. Also gut, dann mal los.[n][uf 1 1][e]

[msg MSG_076_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12012 0 0]Oh, wenn das nicht [uf 4 1] ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0]Du bist auf der Höhe deiner Pubertät, oder? Dann solltest du mir gut zuhören ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Kostenlos, versteht sich.[n][uf 1 1][e]

[msg MSG_077_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Habe ich deine Aufmerksamkeit? Dann hör lieber gut zu.[n][uf 1 1][e]

[msg MSG_078_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12071 0 0]*seufz*[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Oh, [uf 4 1]. Möchtest du eine weitere Lebenslektion?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Wie gewöhnlich ist sie kostenlos.[n][uf 1 1][e]

[msg MSG_079_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12050 0 0]Verstehe. Immerhin bist du ehrlich, junge Dame.[n][uf 1 1][e]

[msg MSG_080_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12009 0 0]Ah, [uf 4 1]. Guten Abend.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Sehnst du dich nach einer weiteren Lebenslektion? Es steht dir ins Gesicht geschrieben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Sie ist natürlich vollkommen kostenlos.[n][uf 1 1][e]

[msg MSG_081_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Oh, welch Enthusiasmus. Hängst du mir etwa völlig an den Lippen?[n][uf 1 1][e]

[msg MSG_082_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12065 0 0]Ah, [uf 4 1]. Du kommst gerade recht.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Du bist nicht gerade beschäftigt, oder? Denn ich habe eine wertvolle Lektion für dich![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Sie ist natürlich vollkommen kostenlos.[n][uf 1 1][e]

[msg MSG_083_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12067 0 0]Ausgezeichnet. Deine Begeisterung ist wirklich entzückend.[n][uf 1 1][e]

[msg MSG_084_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12008 0 0]Oh, wenn das nicht [uf 4 1] ist.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Ich kann dir eine Lebensweisheit erzählen, die du nicht verpassen solltest.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Und sie ist ganz und gar gratis.[n][uf 1 1][e]

[msg MSG_085_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Verstehe ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Für heute habe ich eine druckfrische Story für dich.[n][uf 1 1][e]

[msg MSG_086_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12093 0 0]Du kommst häufig zu mir, [uf 4 1]. Irgendetwas muss ich wohl richtig gemacht haben.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Der Wert der Lebenslektion liegt wohl im Auge des Betrachters.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0]Die hier ist kostenlos.[n][uf 1 1][e]

[msg MSG_087_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12067 0 0]Ausgezeichnet. Ich habe auf einen ... ah, nicht so wichtig.[n][uf 1 1][e]

[msg MSG_088_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 0 65535 65535 0 0][uf 3 1 3 0 65535 12012 0 0]Oh, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Ich habe eine Lebensweisheit im Sinn, auch wenn sie nicht unbedingt für dich gilt. Bist du trotzdem interessiert?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0]Sie ist vollkommen gratis.[n][uf 1 1][e]

[msg MSG_089_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 1 65535 65535 0 0][uf 3 1 3 0 65535 12094 0 0]Dann warten wir nicht länger. Die Uhr tickt. Aufgepasst.[n][uf 1 1][e]

[msg MND_090_0_0]
[uf 0 5 65278][uf 2 1]Ich sollte nach ein andermal nach meiner Investition fragen ...[n][uf 1 1][e]

[msg MSG_220_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie ergreifen bloß nicht die Gelegenheit.[n][uf 1 1][e]

[msg MSG_221_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie lassen bloß die Gelegenheit verstreichen.[n][uf 1 1][e]

[msg MSG_222_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie vergeuden bloß die Gelegenheit.[n][uf 1 1][e]

[msg MSG_223_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie sehen bloß nicht die Gelegenheit.[n][uf 1 1][e]

[msg MSG_224_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie fürchten bloß die Gelegenheit.[n][uf 1 1][e]

[msg MSG_225_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie lassen bloß die Gelegenheit verstreichen.[n][uf 1 1][e]

[msg MSG_226_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, ihnen fehlt bloß die Initiative.[n][uf 1 1][e]

[msg MSG_227_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie denken bloß nicht an die Gelegenheit.[n][uf 1 1][e]

[msg MSG_228_0_0 [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1][uf 4 5 113 3 65535 65535 0 0][uf 3 1 3 0 65535 12014 0 0]Hmpf ... Es ist nicht so, dass die Armen keine Chance haben, sie bemerken nur die Gelegenheit erst, wenn es zu spät ist.[n][uf 1 1][e]

[msg MND_GENERAL_EVENTPLAY]
[uf 0 5 65278][uf 2 1]Message issued by the script. [n][uf 1 5 0]Comm Event Replay.[n][uf 1 1][e]

[msg MND_GENERAL_PERSPNA]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass wir uns dank der [uf 2 4 2]-Persona näherkommen, [uf 0 1 35][uf 2 4 5][uf 0 1 27].[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung[n]zwischen mir und [uf 2 4 0].[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_MAX]
[uf 0 5 65278][uf 2 1]Ich spüre eine unzerbrechliche Bindung zwischen mir und dem alten Paar ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_RAN]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass [uf 2 4 0] und ich uns schon bald näherkommen.[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_RANKUP]
[uf 0 5 65278][uf 2 1]Ich habe das Gefühl, dass das alte[n]Paar und ich uns bald näherkommen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_NOR]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn ich mehr[n]Zeit mit [uf 2 4 0] verbringe ...[n][uf 1 1][e]

[msg MND_GENERALMSG_BS_NORMAL [Präsident Tanaka]]
[uf 0 5 65278][uf 2 1]Ich glaube nicht, dass unsere Bindung sich[n]weiter vertiefen wird, auch wenn wir[n]mehr Zeit miteinander verbringen ...[n][uf 1 1][e]

[msg MND_GENERALSELECTMSG_MAX_2]
[uf 0 5 65278][uf 2 1]Noch besser kann unsere Beziehung wohl nicht werden ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]Sollen wir trotzdem Zeit miteinander verbringen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_AS]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule Zeit mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_DT]
[uf 0 5 65278][uf 2 1]Soll ich den Tag mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[msg MND__GENERAL_MSG_NET]
[uf 0 5 65278][uf 2 1]Soll ich eine Weile das Online-MMORPG mit spielen ...?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_SOLO_NT]
[uf 0 5 65278][uf 2 1]Soll ich den Abend[n]mit [uf 2 4 0] verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_SOL top]
[uf 0 5 65278][uf 2 1]Zeit mit [uf 2 4 0] verbringen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MND_GENERAL_MSG_MULTIPLE]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule hier etwas Zeit [n]verbringen: [uf 2 4 1]?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_FASHION_]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]beim Modeclub verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR]
[uf 0 5 65278][uf 2 1]Soll ich den Tag im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_BOOKSTOR_2]
[uf 0 5 65278][uf 2 1]Soll ich nach der Schule etwas Zeit[n]im Antiquariat verbringen?[n][uf 1 1][e]

[msg MND_GENERAL_MSG_MULTIPLE_2]
[uf 0 5 65278][uf 2 1]Soll ich mit [uf 2 4 1] die Nacht verbringen?[n][uf 1 1][e]

[sel SEL_GENERALSELECTMSG_MUL top]
[uf 0 5 65278][uf 2 1]Beim [uf 2 4 1] mitmachen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_FCL top]
[uf 0 5 65278][uf 2 1]Zum Modeclub gehen[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[sel SEL_GENERALSELECTMSG_BS top]
[uf 0 5 65278][uf 2 1]Das Antiquariat betreten[e]
[uf 0 5 65278][uf 2 1]Social-Link anzeigen[e]
[uf 0 5 65278][uf 2 1]Lieber nicht[e]

[msg MSG_GENERAL_EXAMREWARD_0 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_2]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_2 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_3 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4077 0 0]Oh, stimmt. Eines wollte ich noch sagen ...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_4 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Hier, von Shuji.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Das ist eine Belohnung dafür, dass du die Schule und ... unsere "extrakurrikulären Aktivitäten" so gut vereinst.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_4]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_5 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_0_5]
[uf 0 5 65278][uf 2 1]未使用ラベルです。
[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_0_6 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 6 65535 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

[msg MSG_GENERAL_EXAMREWARD_1 [Mitsuru Kirijo]]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4029 0 0]Ah, [uf 4 1].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Ich habe deine Prüfungsergebnisse gesehen ... Gute Arbeit.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 0 65535 65535 0 0]Deine schulischen Leistungen sind bewundernswert, wenn man bedenkt, wie viele schwere Kämpfe du austrägst.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4108 0 0]Hier ist eine kleine Anerkennung für deine harte Arbeit.[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_2]
[uf 0 5 65278][uf 2 1]DEV: UNUSED LABEL[n][uf 1 1][e]

[msg MND_GENERAL_EXAMREWARD_1_3]
[uf 0 5 65278][uf 2 1]Da ich Erster bei den Prüfungen bin, habe ich auch dies erhalten: [uf 4 4 1 37 1 3].[n][uf 1 1][e]

